#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03! (cl).
# Generated 12:39:28 24 Jul 2003
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	cl
LD  	=	g++
WRES	=	windres
HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
libDirs	=
incDirs	=	-I../BFC

LD_FLAGS =	-s
LIBS	=	
C_FLAGS	=	-O

SRCS	=\
	../BFC/CBfc_2dRect.cpp\
	../BFC/CBfc_2dSize.cpp\
	../BFC/CBfc_Array.cpp\
	../BFC/CBfc_CompressionAlgorythm.cpp\
	../BFC/CBfc_Distance.cpp\
	../BFC/CBfc_Exception.cpp\
	../BFC/CBfc_File.cpp\
	../BFC/CBfc_LinkedList.cpp\
	../BFC/CBfc_MatrixDoubles.cpp\
	../BFC/CBfc_Moment.cpp\
	../BFC/CBfc_PointSpaceTime.cpp\
	../BFC/CBfc_ReferencedObject.cpp\
	../BFC/CBfc_Stream.cpp\
	../BFC/CBfc_String.cpp\
	../BFC/CBfc_Value.cpp\
	../BFC/character.cpp\
	../BFC/Strcore.cpp\
	../BFC/Bfc_DebugStatic.c

EXOBJS	=\
	$(oDir)/CBfc_2dRect.o\
	$(oDir)/CBfc_2dSize.o\
	$(oDir)/CBfc_Array.o\
	$(oDir)/CBfc_CompressionAlgorythm.o\
	$(oDir)/CBfc_Distance.o\
	$(oDir)/CBfc_Exception.o\
	$(oDir)/CBfc_File.o\
	$(oDir)/CBfc_LinkedList.o\
	$(oDir)/CBfc_MatrixDoubles.o\
	$(oDir)/CBfc_Moment.o\
	$(oDir)/CBfc_PointSpaceTime.o\
	$(oDir)/CBfc_ReferencedObject.o\
	$(oDir)/CBfc_Stream.o\
	$(oDir)/CBfc_String.o\
	$(oDir)/CBfc_Value.o\
	$(oDir)/character.o\
	$(oDir)/Strcore.o\
	$(oDir)/Bfc_DebugStatic.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/BFCHome.lib
ALLTGT	=	$(Bin)/BFCHome.lib

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/BFCHome.lib: $(EXOBJS)
	rm -f $(Bin)/BFCHome.lib
	ar cr $(Bin)/BFCHome.lib $(EXOBJS)
	ranlib $(Bin)/BFCHome.lib
