//*/
/*
					CImgPipe.cpp : 
	
		This source file is part of the BFC Engine.
		
	Author: William P. Foster (bill@software0imagination.com)

// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 William P. Foster
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
*/

//*/
//                                                                               
// $Header:   J:/DA.arc/docimg/CImgPipe.cpv   1.2   02 May 2003 13:23:44   KArdebil  $                                                                   
// $Revision:   1.2  $                                                                 
//                                                                              
// Copyright (c) Xerox Corporation 1991, ..., 2003.  All rights reserved. 
//                                                                              

/*
	CImgPipe.cpp - Image processing control for images.
					Relies on the SandPiper library.

  Todo:
	  Remember always about the differencing predictor, 
			and smoothing support for LZW and JPEG.

  put in the logic to automatically Calculate_AutomaticLossAdjustment() on <16 bits per pixel. 

  Importing:
	Ask crew: how important is it that all internal files are stored in tiff format (ok, - use LZW)?
	Use a lot of the same options.  Allow user to import to jpeg internal, etc.
	Images will be kept in this format
	Keep a tag inside of .tiff files that has all of the pre-calculated information
		that is generated by Calculate_AutomaticLossAdjustment().

   The fun part: 
	  ALA: Automatic Loss Adjustment.
	  Calculate Smoothing, and loss factor
	  LZW extra variable (predictor)

  Security Checks:
		Make sure the is enough disk space before writing files - Done.

  Initial Default settings :
	ALA on, Quality of 8.
	TIFF, Automatic everything.
*/

#if 0

#ifdef XTIP_PROJECT
#	include <stdafx.h>
#endif
#include <CImgPipe.h>
#include   <math.h>
#include  <emacro.h>
#include  <direct.h>       // ffblk, MAXPATH
#include <process.h>
#include "resource.h"
#include <ipam\ipam.h>
#include <icm.h>
#include <io.h>
#include <fcntl.h>



#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif



#define swap(a,b)           {a^=b; b^=a; a^=b;}
#define absolute(i,j,k)     ( (i-j)*(k = ( (i-j)<0 ? -1 : 1)))

extern Error* error;

Make_Temp_Fname (int iCheckSize,LPCTSTR csBasename,LPTSTR csOutname);

//
// Get the drive number of the given path name. If the pathname does not
// specify a disk drive, the current drive is used.
//
//  Argument | What It Is/Does
// ===========================================================================
//  path     | Points to a string that names the path name.
//
// Return Value:
//  * Returns the current drive number (1 = A, 2 = B, 3 = C, etc.)
//
int getDrive(const TCHAR *path)
{
	int drive = 0;
#ifndef _UNIX
	/*
	 * Check for a drive name. If one is not provided,
	 * get the current drive.
	 */
	if(_istalpha(path[0]) && path[1] == _T(':'))
		drive = _totupper(path[0]) - _T('A') + 1;
	else
		drive = _getdrive();
#endif
	return(drive);
}

//
// Get the disk free space in bytes.
//
//  Argument | What It Is/Does
// ===========================================================================
//  path     | Points to a string that names the path name.
//
// Return Value:
//  * On success returns the available space on the drive.
//  * Otherwise, returns -1 and sets error to one of the following:
//    ENODST  No such destination file or directory
//
LONGLONG getDiskFree(const TCHAR *path)
{
#ifndef _UNIX
	double avail = 0;
	TCHAR dd[_MAX_PATH];
	ULARGE_INTEGER freeBytesToCaller, totalBytes, totalFreeBytes;

	int drive = getDrive(path);
	if(path[0] == _T('\\') && path[1] == _T('\\')) {
		_tcscpy(dd, path);
		TCHAR *slash = _tcsrchr(dd, _T('\\')); 
		if(slash)
			*(_tcsinc(slash)) = NULL;
	}
	else if( drive == 0 ) {
		/*
		 * If dst is not a UNC format nor a drive based format and
		 * the current directory is a network directory not mapped to any drive.
		 */
		if(!GetCurrentDirectory(_MAX_PATH, dd) )
			errorR( ENODST, -1 );
	}
	else {
		dd[0] = drive - 1 + _T('A');
		dd[1] = _T(':');
		dd[2] = _T('\\');
		dd[3] = NULL;
	}
	/*
	 * Check for free disk space on destination path.
	 */
	if((GetDiskFreeSpaceEx((LPCTSTR) dd,
		(PULARGE_INTEGER) &freeBytesToCaller,
		(PULARGE_INTEGER) &totalBytes,
		(PULARGE_INTEGER) &totalFreeBytes)) != TRUE)
		errorR(ENODST, 0);
	return freeBytesToCaller.QuadPart;
#else
	return(getdiskfree(path));
#endif // _UNIX
}


static int getheaderbitsperpixel (HEADER *hdr)
{
	int		i, iaParts[8], iaBits[8], iBits;

	getheaderparts (hdr, &iaParts[0]);
	getheaderbits (hdr, &iaBits[0]);
	for (i=0, iBits = 0; i<iaParts[0]; i++) iBits += iaBits[i];
	return iBits;
}

BOOL CImgPipe::GetInfo (int *ipW, int *ipH, int *ipBits, double *dpDPI, int *ipMask)
{
	int			i;
	HEADER		*hdr;
	Instance	*inTTask;				// Temporary task pointer.

	if (!(m_task = BeginSource())) return FALSE;
	inTTask = ApplyConversions(m_task);
	if (inTTask) m_task = inTTask;

	if (!(hdr = XTHeader (m_task))) {
		*ipW = m_task->pixels;		*ipH = m_task->scanlines;
		for (i=0, *ipBits = 0; i<*(m_task->parts); i++) *ipBits += m_task->bits[i];
		XTEnd (m_task);
		return FALSE;
	}
	if (ipW) getheaderdimensions (hdr, ipW, ipH);
	if (dpDPI) getheaderfield (hdr, "Origin", "resolution", SP_DOUBLE, (char*)dpDPI);
	if (ipBits) *ipBits = getheaderbitsperpixel (hdr);
	if (ipMask) *ipMask = maskvalid(hdr);
	XTEnd (m_task);
	return TRUE;
}

CImgPipe::CImgPipe ()
{
	m_sInFileName = NULL;
	m_bBlank = false;
	m_MergeFiles[0].sFileName = NULL;
	m_task = NULL;
}

/* CImgPipe destructor 
		Frees the strings associated with the list of merge files.
*/
CImgPipe::~CImgPipe ()
{
	int iIndex = 0;
	while (m_MergeFiles[iIndex].sFileName) {
		delete (m_MergeFiles[iIndex].sFileName);
		iIndex++;
	}
}

/*
*/
Instance *CImgPipe::ApplyResolution (Instance *task,int iDPISet,int iBits)
{
	HEADER	*hdr;
	double	dDPI;
	int		iDPI;

	if (task && (hdr = XTHeader (task))) {
		getheaderfield (hdr, "Origin", "resolution", SP_DOUBLE, (char*)&dDPI);
		if (((iDPI = (int)dDPI) > 0) && iDPI != iDPISet) {
			if (iBits == 1) {
				double dEfactor = 3.0;
				/* For single bit images, assume they were scanned and appy some Edge factor */
				task = XTInitTask (init_rescon,"link",task,"resolution",&iDPI,&(iDPISet),"efactor",&dEfactor,ARG_END);
			} else {
				task = XTInitTask (init_rescon,"link",task,"resolution",&iDPI,&(iDPISet),ARG_END);
			}
		}
	}
	return task;
}

BOOL CImgPipe::IsAnyConversions ()
{
	if (ExportSettings.iResolution > 0 ||
		ExportSettings.iColorSpace() != CSPACE_AUTOMATIC ||
		ExportSettings.iBitsPerPixel > 0 ||
		!IS_DBL_EQUAL (ExportSettings.dScale, 1.0)
		|| ExportSettings.iWidth > 0
		) return TRUE;
	return FALSE;
}
/* 
  Instance *CImgPipe::ApplyConversions (Instance *task,int iBits)

  Applies the conversions associated with the member ExportOptions to a pipe being passed in task.
  Applies changes to Bits per pixel, adds Dithering if necessary, changes the Color Space,
	and adds or removes the Mask channel if necessary.
	Doesn't touch or look at m_task.

  ARGUMENTS:
	Instance *task : Instance of a SandPiper pipe.
		 int iBits : Gives a little pre-determined info about the input Instance :
						specifically, the number of bits per pixel.

  RETURN VALUE : The resultant SandPiper Instance*.

*/
Instance *CImgPipe::ApplyConversions (Instance *task,int iBits)
{
	HEADER		*hdr;
	Instance	*insTemp;
	char		*cpSpace = NULL;	// NOT _TCHAR !
	int			iChannels = 3;
	int			ipBits[8];			// Set to Max # of channels + 1
	int			iMaxBits = 32;

	if (ExportSettings.iResolution > 0) {
		task = ApplyResolution (task, ExportSettings.iResolution, iBits);
		if (!task) return NULL;
	}

			// Change the color space
	switch (ExportSettings.iColorSpace()) {
		case CSPACE_YCBCR:
			cpSpace = "YCbCr";
			break;
		case CSPACE_CMYK:
			cpSpace = "cmykLinear";
			iChannels = 4;
			break;
		case CSPACE_LAB:
			cpSpace = "CIELAB";
			break;
		case CSPACE_GRAY:
			cpSpace = "grayLinear";
			iChannels = 1;
			break;
		case CSPACE_INDEXED_RGB:
			cpSpace = "BuildMap";
			iChannels = 1;
			break;
		case CSPACE_RGB:
			cpSpace = "rgbLinear";
			break;
	}
	if (cpSpace) {
		if (!strcmp (cpSpace,"BuildMap")) {

			if ((hdr = XTHeader (task))) {
				Instance	*insT;
				int			tMap[768];
				int			iMapsize = 256, iType, iBits;

				getheaderphotometry (hdr, &iType, NULL);
				iBits = getheaderbitsperpixel (hdr);
				// Convert only if we are not already in indexed color, or reducing the bit size.
				if (iType != BUILDMAP || (ExportSettings.iBitsPerPixel && ExportSettings.iBitsPerPixel < iBits))
				{
					if (ExportSettings.iBitsPerPixel) iMapsize = 1 << ExportSettings.iBitsPerPixel;
					if (iType == GRAYLINEAR) {
						// Auto generate map for grayscale.
						for (int i=0; i < iMapsize-1; i++) {
							tMap[(i*3)+0] = tMap[(i*3)+1] = tMap[(i*3)+2] = (i*256)/iMapsize;
						}
						tMap[(i*3)+0] = tMap[(i*3)+1] = tMap[(i*3)+2] = 255;	// Last color is white.
					} else {
						// Split this task apart!
						task = XTInitTask (init_nbranch,"link",task,ARG_END);
						if ((insT = XTInitTask (init_nbranch,"primary",task,ARG_END))) {
							GeneratePalette (insT, tMap,iMapsize);
							XTEnd (insT);
						}
					}

//					if (ExportSettings.bDither) 
					{
						// Steinberg currently requires scanline interleave (5.1.1+ deficiency).
						insTemp = XTInitTask (init_convert, "link", task, "interleave", "scanline", ARG_END);
						if (insTemp) task = insTemp;
						task = XTInitTask (init_steinberg,"link",task,"random","map","ncolors",&iMapsize,"colormap",tMap,ARG_END);
					} 
//					else {
//						task = XTInitTask (init_tomap,"link",task,"diverse","entries",&iMapsize,"colormap",tMap,ARG_END);
//					}
				}
			}
		} else 
			task = XTInitTask (init_cspace,"link",task,"space",cpSpace,"precise",ARG_END);
		if (!task) return NULL;
	}

	// Apply an ICC color profile...
	if (ExportSettings.szColorProfile)
	{
//		task = XTInitTask (init_xeicc,"link",task,"iccfile","c:/Winnt/system32/color/openrgb.icm",NULL,ARG_END);
		task = XTInitTask (init_xeicc,"link",task,"iccfile",ExportSettings.szColorProfile,NULL,ARG_END);
		if (!task) return NULL;
	}

	// Change the number of bits per pixel/sample if non-zero (non-auto)
	if (ExportSettings.iBitsPerPixel && ExportSettings.iColorSpace() != CSPACE_INDEXED_RGB) {
		if (ExportSettings.iBitsPerPixel <= 8 || ExportSettings.iBitsPerPixel == 16) {
			int	iNbits = 1;

			ipBits[0] = (ExportSettings.iBitsPerPixel == 16) ? 5 : ExportSettings.iBitsPerPixel;
			ipBits[1] = 0;
			task = XTInitTask (init_convert, "link", task, "bits", ipBits, "nbits", &iNbits, ARG_END);

			if (!task) return NULL;
		}
	}

/*
	// Perform Dithering (if necessary)
	if (ExportSettings.bDither && ExportSettings.iBitsPerPixel < 9) {
		int		iLevels;

		if ((hdr = XTHeader (task))) {
			getheaderbits (hdr, &ipBits[0]);
			if (ipBits[0] > ExportSettings.iBitsPerPixel) {
				iLevels = pow (2,ExportSettings.iBitsPerPixel);
				task = XTInitTask (init_floyd, "link", task, "levels", &iLevels, ARG_END);
				if (!task) return NULL;
			}
		}
	}
*/
		/* Create a Thumbnail in the header of the image */
/*
    Look at ImageGear
	if (ExportSettings.bCreateThumbnails) {
	}
*/
/*
		// Add or remove an Alpha Opacity Mask channel if need be.
	if ((hdr = XTHeader (task))) {
		switch (ExportSettings.bAlpha) {
			case 2:				// Third state - don't force Alpha On or Off.
				break;
			case 1:
				if (!maskvalid(hdr)) {		// Alpha channel is not there: Add One (all FF's).
					task = XTInitTask (init_channel, "link", task, "command", "Assign Mask A 255", NULL, ARG_END);
					iChannels++;
				}
				break;
			case 0:
				if (maskvalid(hdr)) {		// Extra Alpha Channel(s): Remove it(them).
					task = XTInitTask (init_channel, "link", task, "command", "Delete Mask *",NULL, ARG_END);
					iChannels--;
				}
				break;
		}
	}
*/	
	return task;
}

/*
	Make_Temp_Fname (int iCheckSize,LPCTSTR csBasename,LPTSTR csOutname);

  ARGUMENTS:
	csBasename : If non-NULL, first attempts to store file in same folder as this file.
	 csOutname : A Buffer that will receive the name of the temporary file.  Should be MAX_PATH characters long.

  RETURN VALUE : TRUE on success, FALSE on failure.
*/
Make_Temp_Fname (int iCheckSize,LPCTSTR csBasename,LPTSTR csOutname)
{
	TCHAR	*csFolder=NULL;

	if (csBasename) {
		TCHAR *tcp = _tcsrchr(csBasename,_T('\\'));

		if (tcp) {
			csFolder = _tcsdup (csBasename);
			*_tcsrchr(csFolder,_T('\\')) = _T('\0');
		}
	}
#ifndef _UNIX
	if (!csFolder) {
		csFolder = new TCHAR[_MAX_PATH];
		GetTempPath (_MAX_PATH, csFolder);
	}
	GetTempFileName (csFolder, _T("jpg"), 0, csOutname );
#endif
	if (csFolder) delete csFolder;
	return TRUE;
}




/***************************************************************************/
/***************************************************************************/
/****                                                                   ****/
/****           Define a pseudo-XTIP function that invokes the          ****/
/****             Windows Color Management                              ****/
/****                                                                   ****/
/****           Use this pseudo function with the user(3x) XTIP         ****/
/****             function                                              ****/
/****                                                                   ****/
/***************************************************************************/
/***************************************************************************/

/*
** Define the private data fr your pseudo-XTIP function
*/
typedef struct _myInstance
{
  HTRANSFORM hTransform;
  HPROFILE   hDestProfile;
  int iPixels;
  int iScanlines;
  int iPitch;
  unsigned char *inbuf;
} myInstance;


/*
*/
long MakeFix (double fVal, int remainderBits)
{
	unsigned long	dRval;

	dRval = (int)fVal; 
	fVal -= dRval;
	dRval <<= remainderBits;
	dRval |= (int)(fVal * (1 << remainderBits));
	return (long)dRval;
}

// Calculates fixed poit from floating point.
#define __FXPTMANTISSA(d, f)  ( (DWORD)d << f )
#define __FXPTFRACTION(d, f)  ( (DWORD)ldexp((d - (DWORD)d), f) )
#define __FXPT32(d, f)      ( __FXPTMANTISSA(d, f) | __FXPTFRACTION(d, f) )

#define __FXPT2DOT30(d)   __FXPT32(d, 30)
#define __FXPT16DOT16(d)  __FXPT32(d, 16)

/*
** Initialize provate data in your pseudo-XTIP function
*/
int myInit(char **argv, char **userDataPtr)
{
  myInstance *myins;

  char *szProfileFile;
  PROFILE         prof;
  LOGCOLORSPACE   lCspace;

  /*
  ** Allocate the private data ds
  */
  myins = (myInstance*)calloc(1, sizeof(myInstance));

  /*
  ** Open the desired profile
  */
  xtScanArgs(NULL, argv, "profile", 0L, &szProfileFile);

  prof.dwType = PROFILE_FILENAME;
  prof.pProfileData = (PVOID) szProfileFile;
  prof.cbDataSize = strlen(szProfileFile);		// bytes
  myins->hDestProfile = OpenColorProfile(&prof, PROFILE_READ, FILE_SHARE_READ, OPEN_EXISTING);
//  if (!hDestProfile) {
//      iRval = false;
  //    goto l_badrap;
//  }
  lCspace.lcsSignature = LCS_SIGNATURE;
  lCspace.lcsVersion = 0x400;
  lCspace.lcsSize = sizeof(LOGCOLORSPACE);
  lCspace.lcsIntent = LCS_GM_IMAGES;
#if 1
	LPLOGCOLORSPACE	lpColorSpace = &lCspace;
//        lpColorSpace->lcsCSType = LCS_sRGB;
  lCspace.lcsCSType = LCS_CALIBRATED_RGB;

        // Set endpoints to sRGB values.

        lpColorSpace->lcsEndpoints.ciexyzRed.ciexyzX = __FXPT2DOT30(.64);
        lpColorSpace->lcsEndpoints.ciexyzRed.ciexyzY = __FXPT2DOT30(.33);
        lpColorSpace->lcsEndpoints.ciexyzRed.ciexyzZ = __FXPT2DOT30(.03);

        lpColorSpace->lcsEndpoints.ciexyzGreen.ciexyzX = __FXPT2DOT30(.3);
        lpColorSpace->lcsEndpoints.ciexyzGreen.ciexyzY = __FXPT2DOT30(.6);
        lpColorSpace->lcsEndpoints.ciexyzGreen.ciexyzZ = __FXPT2DOT30(.1);

        lpColorSpace->lcsEndpoints.ciexyzBlue.ciexyzX   =   __FXPT2DOT30(  .15);
        lpColorSpace->lcsEndpoints.ciexyzBlue.ciexyzY = __FXPT2DOT30(.06);
        lpColorSpace->lcsEndpoints.ciexyzBlue.ciexyzZ = __FXPT2DOT30(.79);

        // Just so that if monitor has 2.2 gamma, the over all gamma is 1.0.
        lpColorSpace->lcsGammaRed = __FXPT16DOT16(0.45);
        lpColorSpace->lcsGammaGreen = __FXPT16DOT16(0.45);
        lpColorSpace->lcsGammaBlue = __FXPT16DOT16(0.45);
#else
  lCspace.lcsCSType = LCS_CALIBRATED_RGB;
  lCspace.lcsEndpoints.ciexyzRed.ciexyzX = MakeFix (1.8150289, 30);
  lCspace.lcsEndpoints.ciexyzRed.ciexyzY = MakeFix (1.0, 30);
  lCspace.lcsEndpoints.ciexyzRed.ciexyzZ = MakeFix (0.07514451, 30);

  lCspace.lcsEndpoints.ciexyzGreen.ciexyzX = MakeFix (0.45578231, 30);
  lCspace.lcsEndpoints.ciexyzGreen.ciexyzY = MakeFix (1.0, 30);
  lCspace.lcsEndpoints.ciexyzGreen.ciexyzZ = MakeFix (0.244897959, 30);

  lCspace.lcsEndpoints.ciexyzBlue.ciexyzX = MakeFix (2.142857142, 30);
  lCspace.lcsEndpoints.ciexyzBlue.ciexyzY = MakeFix (1.0, 30);
  lCspace.lcsEndpoints.ciexyzBlue.ciexyzZ = MakeFix (3.999, 30);
#endif
  _tcscpy(lCspace.lcsFilename, szProfileFile);
  myins->hTransform = CreateColorTransform(&lCspace, myins->hDestProfile, NULL, BEST_MODE);

  if (userDataPtr != NULL)
    *userDataPtr = (char *)myins;

  return XTNOERROR;
}

/*
** Process the input header in your pseudo-XTIP function
*/
HEADER *myDoHeader(HEADER *inputHeader, char *userData)
{
  myInstance *myins = (myInstance*)userData;

  setheaderphotometry(inputHeader, CIELAB);
  /*
  ** Allocate a work buffer to process data in
  */
  getheaderdimensions( inputHeader, &myins->iPixels, &myins->iScanlines );
  getheadertotalbytes( inputHeader, &myins->iPitch );

  myins->inbuf = (unsigned char *)calloc( myins->iPitch, sizeof(unsigned char) );
  return inputHeader;
}


/*
** Process the scanline in your pseudo-XTIP function
*/
unsigned char *
myProcessScanline( Instance *inputInstance, char *userData, unsigned char *outbuf )
{
  myInstance *myins = (myInstance*)userData;
  DWORD	err;
  BOOL bRval;

  /*
  ** Acquire an input scanline
  */
  XTProcess( inputInstance, myins->inbuf );

  /*
  ** Process the scanline into the output buffer
  */
  bRval = TranslateColors (myins->hTransform, (COLOR *)myins->inbuf, myins->iPixels, COLOR_RGB, (COLOR*)outbuf, COLOR_Lab);
//  bRval = TranslateBitmapBits(
//              myins->hTransform,
//              myins->inbuf, BM_RGBTRIPLETS, myins->iPixels, 1, myins->iPitch,
//              outbuf,       BM_LabTRIPLETS, myins->iPitch, NULL, NULL );

  if (!bRval) err = GetLastError ();
//  memcpy (outbuf, myins->inbuf, myins->iPitch);	// successfully makes duplicate
  return outbuf;
}


/*
** Cleanup your pseudo-XTIP function
*/
void myCleanup( char *userData )
{
  myInstance *myins = (myInstance*)userData;

  /*
  ** Cleanup your allocated resources
  */

  if (!myins)
    return;

  CloseColorProfile(myins->hDestProfile);
  if (myins->inbuf) free( myins->inbuf );

  free( myins );
}

/*
	 CImgPipe::ImportFile ()
	  Convert a single input file to internal LAB format.
	  Performs the color conversion from the original color space to LAB using sProfileFile, if specified,
	  otherwise uses SandPiper.
*/
int CImgPipe::ImportFile (LPCTSTR szInFile, LPCTSTR szOutFile, LPCTSTR szProfileFile, int iOutW, int iOutH)
{
	HEADER			*hdr;
	Instance *		inTTask;				// Temporary task pointer.
	unsigned char	*ucInBuffer;
	int				iLine, iPixels, iScanlines, iPitch;
	int				iRval = true;

	m_sInFileName = szInFile;
	if (!(m_task = BeginSource())) {
		error->set (ERIS);
		return FALSE;
	}
	if (iOutW != -1) {
		// Apply scaling to the input stream.
	}
	if (szProfileFile == NULL) {
		// No import profile specified, use SandPiper to do the whole thing with one Instance *.

	} else {
		// Import profile specified.  Use Microsoft Windows 2000 to convert from input to LAB.
		char	*user_args[10];
		int		ipBits[8];			// Set to Max # of channels + 1

			// Add a channel to the input to get 32 bits per pixel.
		inTTask = XTInitTask (init_channel, "link", m_task, "command", "Assign Mask A 255", NULL, ARG_END);
		if (inTTask) m_task = inTTask;

	ipBits[0] = 16;		ipBits[1] = 0;
	inTTask = XTInitTask (init_convert, "link", m_task, "bits", ipBits, "interleave", "pixel", ARG_END);
	if (inTTask) m_task = inTTask;

		XTBuildArgumentVector(user_args, "profile", szProfileFile, ARG_END);
		inTTask = XTInitTask(init_user,
                      "link", m_task,
                      "arguments", user_args,
                      "init", myInit,
                      "header", myDoHeader,
                      "scanline", myProcessScanline,
                      "cleanup", myCleanup,
                       ARG_END);
		if (inTTask) m_task = inTTask;


	ipBits[0] = 8;		ipBits[1] = 0;
	inTTask = XTInitTask (init_convert, "link", m_task, "bits", ipBits, ARG_END);
	if (inTTask) m_task = inTTask;

		inTTask = XTInitTask (init_channel, "link", m_task, "command", "Delete Mask *",NULL, ARG_END);
		if (inTTask) m_task = inTTask;

		inTTask = XTInitTask (init_writetif, "link", m_task, "file", szOutFile, "packbits", ARG_END);
		if (inTTask) m_task = inTTask;
			// Need to set up the header for the output task to reflect image size and LAB
#if 0
  XTProcessImage(m_task, -1);
#else
		hdr = XTHeader (m_task);
		getheaderdimensions (hdr, &iPixels, &iScanlines);
		getheadertotalbytes (hdr, &iPitch);

		if ((ucInBuffer = new unsigned char[iPitch])) {
			for (iLine = 0; iLine < iScanlines; iLine++) {
				if (XTProcess (m_task, ucInBuffer))			// Input a line from the source file
					break;
			}
			delete ucInBuffer;
		} else
			error->set (ENOMEM);
#endif
	}
	XTEnd (m_task);
	m_task = NULL;
	return iRval;
}


/*
	CImgPipe::ExportFile (LPCTSTR csInFileName, LPCTSTR csOutFileName)
		Write out a new Image file from one or more (merged) files.
		The format for the output file is stored in the ExportOptions class member.

  ARGUMENTS:
	 csInFileName : If non-NULL, the name of the source file.
					If NULL, source is obtanied from merging various files defined by calls
						to CImgPipe::Blank() and CImgPipe::NMerge()
	csOutFileName : Must be specified.   The complete output file name to store the output to.

  RETURN VALUE : TRUE on success, FALSE on failure.
*/
CImgPipe::ExportFile (LPCTSTR csInFileName, LPCTSTR csOutFileName)
{
	HEADER			*hdr;
	int				iLine, iPixels, iScanlines, iPitch;
	int				iQuality = 100, iSmoothing = 0;
	unsigned char	*ucBuffer;
	int				ipParts[8];
	IP_COMPRESSION	iCompression;
	int				i, iBits=0, ipBits[8];	// Set to Max # of channels + 1
	BOOL			bRval = true;
	Instance *		inTTask;				// Temporary task pointer.
//	TCHAR			*sTempJpegFilename = NULL;
	double			dDPI;

	m_sInFileName = csInFileName;

	//
	// If the compression quality issue is resolved, almost any output to JPEG should use IPAM.
	//
//	if (ExportSettings.outputFiletype == FT_JPEG)
//		return RunPipeline2 (csOutFileName);
	if (!IsAnyConversions ()) {
		iCompression = ExportSettings.iOutputCompression();
		if (ExportSettings.outputFiletype == FT_TIFF && iCompression == COMP_G42D)
			return ConvertToG4TIFF (csInFileName, csOutFileName);
		if (ExportSettings.outputFiletype == FT_JPEG)
			return ConvertToJPEG (csInFileName, csOutFileName);
	}

	if (!(m_task = BeginSource())) {
		error->set (ERIS);
		return FALSE;
	}
	if (ExportSettings.iWidth > 0) {
		inTTask = XTInitTask (init_scale, "link", m_task, "awindow", &ExportSettings.iWidth, &ExportSettings.iHeight, ARG_END);
		if (inTTask==NULL) { 
			error->set (ERIS);		// Replace with  new message when we make a 30docimg.rc
			bRval = false;		goto lCleanup; 
		}
		m_task = inTTask;
	}
	if (!IS_DBL_EQUAL (ExportSettings.dScale, 1.0)) {
		 // Scale it 
		inTTask = XTInitTask (init_scale, "link", m_task, "factor", &ExportSettings.dScale, ARG_END);
		if (inTTask==NULL) { 
			error->set (ERIS);		// Replace with  new message when we make a 30docimg.rc
			bRval = false;		goto lCleanup; 
		}
		m_task = inTTask;
	}

	hdr = XTHeader (m_task);
	getheaderparts (hdr, &ipParts[0]);
	if (getheaderbits (hdr, &ipBits[0]))
		for (i=0, iBits = 0; i<ipParts[0]; i++) iBits += ipBits[i];

	iCompression = ExportSettings.iOutputCompression();
	if (iCompression == COMP_AUTOMATIC && ExportSettings.iBitsPerPixel <= 1 && iBits == 1) iCompression = COMP_G42D;	// Monochrome automatic CCIT-G4-2D

				// Automatically Adjust the loss setting and detrmine best compression for this image
	if ((ExportSettings.outputFiletype == FT_JPEG || ExportSettings.outputFiletype == FT_TIFF) 
			&& (iCompression == COMP_JPEG_LOSSY || iCompression == COMP_AUTOMATIC))
	{
		iQuality = ExportSettings.jpegSettings.iQuality;
		iSmoothing = ExportSettings.jpegSettings.iSmoothing;

		if (ExportSettings.jpegSettings.bAutoLossAdjustment || iCompression == COMP_AUTOMATIC) {
			int	iAcceptableLoss;
			IP_COMPRESSION iComp;

			iQuality = 100;		// start from scratch
			iAcceptableLoss = Calculate_AutomaticLossAdjustment (iCompression == COMP_AUTOMATIC, &iComp);
//			iQuality -= (iAcceptableLoss-50)/2;
			iQuality = 100 - min(iAcceptableLoss,75);

			if (iQuality > 100) iQuality = 100;
			else if (iQuality < 1) iQuality = 1;

			if (iCompression == COMP_AUTOMATIC) {
				switch(ExportSettings.outputFiletype) {
					case FT_TIFF:
						iCompression = iComp;		// Calculated Value is a valid Tiff compression scheme
						if (iComp == COMP_G42D && ExportSettings.iBitsPerPixel > 1) 
							iCompression = COMP_PACKBITS;
						break;
					case FT_JPEG:
						// Calculated Value is a valid TIFF compression scheme (not JPEG).
						if (iComp == COMP_JPEG_LOSSLESS || iComp == COMP_JPEG_LOSSY)
							iCompression = iComp;
						else {
							if (iAcceptableLoss < 5)	// For JPEGS, we must calculate a compression scheme based
								iCompression = COMP_JPEG_LOSSLESS;	// on the acceptable loss value.
							else
								iCompression = COMP_JPEG_LOSSY;
						}
						break;
				}
			}
		}
	}

	inTTask = ApplyConversions (m_task, iBits);		// Set up the SandPiper pipes.
	if (inTTask==NULL) { 
		error->set (ERIS);		// Replace with  new message when we make a 30doc.rc
		bRval = false;		goto lCleanup; 
	}
	if (ExportSettings.iRotateDegrees) {
		m_task = inTTask;
		inTTask = ApplyRotation (m_task, ExportSettings.iRotateDegrees);
		if (inTTask==NULL) { 
			error->set (ERIS);		// Replace with  new message when we make a 30doc.rc
			bRval = false;		goto lCleanup; 
		}
		m_task = inTTask;
	}

//// Take a debug look at the header ////
	hdr = XTHeader (m_task);
	getheaderdimensions (hdr, &iPixels, &iScanlines);
	getheadertotalbytes (hdr, &iPitch);

	/* Check the destination for enough disk space. */

	if (getDiskFree (csOutFileName) < iPitch * iScanlines) {
		error->set (ENODISK);
		bRval = false;	goto lCleanup;
	}

	
////////////////////////////////////////
	
	inTTask = m_task;
	switch (ExportSettings.outputFiletype) {
		case FT_JPEG:
			inTTask = XTInitTask (init_writejpg, "link", m_task,	"file", csOutFileName,
								"quality",  &iQuality, "smoothing", &iSmoothing,
//								"resolution", double,
					ARG_END);
			break;
		case FT_TIFF:
			{
				bool	bDoWrite = true;
				char	*sCompr = NULL;		// NOT _TCHAR !

				switch (iCompression)
				{
					case COMP_JPEG_LOSSLESS:
					case COMP_JPEG_LOSSY:
					/* If compression type is JPEG, we have to write a JPEG and then make it as TIFF */
//						hdr = XTHeader (m_task);
//						getheaderdimensions (hdr, &iPixels, &iScanlines);
//						getheadertotalbytes (hdr, &iPitch);
					/* Get Temp filepath */
//						sTempJpegFilename = new TCHAR[MAX_PATH];
//						if (sTempJpegFilename && Make_Temp_Fname (iPitch * iScanlines, csOutFileName, sTempJpegFilename))
//						{
//							if (getDiskFree(sTempJpegFilename) < iPitch * iScanlines) {
//								error->set (ENODISK);
//								{ bRval = false;	goto lCleanup; }
//							}
//							inTTask = XTInitTask (init_writejpg, "link", m_task, "file", sTempJpegFilename,
//													"quality",  &iQuality, "smoothing", &iSmoothing,
//													ARG_END);
//						}
//						bDoWrite = false;
						sCompr = "jpeg";
						break;
					case COMP_G42D:
						sCompr = "ccitt";
						ipParts[0] = 4;
						ipParts[1] = 0;
						inTTask = XTInitTask (init_writetif, "link", m_task, "file", csOutFileName,
												"ccitt", ipParts, ARG_END);
						bDoWrite = false;
						break;
//					case COMP_LZW:
//						sCompr = "lzw";
						// Provide a predictor value.
//						break;
					case COMP_PACKBITS:
						sCompr = "packbits";
						break;
					case COMP_UNCOMP:
						break;
					case COMP_AUTOMATIC:	/* Best compression should already be determined for this image */
						break;
				}
				if (bDoWrite)
					inTTask = XTInitTask (init_writetif, "link", m_task, "file", csOutFileName,
										sCompr ? sCompr : ARG_END, ARG_END);
			}
			break;
		case FT_PDF:
			/* Will not arrive here - uses the old method */
			break;
		case FT_POSTSCRIPT:
			break;
		case FT_XTIP:
			break;
	}
	if (inTTask==NULL) { 
		error->set (EDSTACS);
		bRval = false; goto lCleanup; 
	}
	m_task = inTTask;

	hdr = XTHeader (m_task);
	getheaderdimensions (hdr, &iPixels, &iScanlines);
	getheadertotalbytes (hdr, &iPitch);
	getheaderparts (hdr, &ipParts[0]);
	getheaderfield (hdr, "Origin", "resolution", SP_DOUBLE, (char*)&dDPI);

#if 0
	XTProcessImage (m_task, 1);
#else
	if ((ucBuffer = new unsigned char[iPitch])) {
		for (iLine = 0; iLine < iScanlines; iLine++) {
			if (XTProcess (m_task, ucBuffer))
				break;
		}
		delete ucBuffer;
	} else
		error->set (ENOMEM);
#endif

		/* cleanup and release XTIP pipeline */
lCleanup:
	XTEnd (m_task);
//	if (sTempJpegFilename) {
//		if (bRval) {
//			bRval = Make_JPEG_TIFF (sTempJpegFilename,csOutFileName,iPixels,iScanlines,(int)dDPI);
//		}
//		unlink (sTempJpegFilename);
//		delete sTempJpegFilename;
//	}
	m_task = NULL;
	return bRval;
}

/* 
Instance *CImgPipe::ApplyRotation(Instance *task, int iAngle)

  ARGUMENTS:
	  iAngle : Angle in degrees.  Must be a multiple of 90 and not more than 270.
  RETURN VALUE:
	Will always return a valid Instance pointer if passed one. 
*/
Instance *CImgPipe::ApplyRotation(Instance *task, int iAngle)
{
	Instance	*tt;
	char		*csAngle;

	if (!task) return NULL;
	switch (iAngle) {
		case 0:
			return task;
		case 90:
			csAngle = "-90";
			break;
		case 180:
			csAngle = "180";
			break;
		case 270:
			csAngle = "90";
			break;
	}
	tt = XTInitTask (init_rotate90, "link", task, "angle", csAngle, ARG_END);
	return tt ? tt : task;
}
/* 
Instance *CImgPipe::BeginSource (void)
	Sources the input file(s).  will use a single filename, m_sInFileName, if Non-NULL,

	Else, puts together multiple images that were specified by calls on this CImgPipe 
		to Blank() and NMerge();
		Uses the dpi of the first source as the master dpi.
*/
Instance *CImgPipe::BeginSource (void)
{
	int			iIndex;
	Instance	*tt, *source, *primary;
	HEADER		*hdr;
	double		dDPI;
	int			iForceResolution = 200;			// Set all input files to this value!
	bool		iFirstFile = true;

	setappversion ("2.1");				// make sure 2.1 headers are set.

	if (m_sInFileName) return XTSource (0,m_sInFileName);

	source = NULL;
	if (m_bBlank) {
		////////////////////////////////////////////////////////
		// gray background 0-255
		// 
		////////////////////////////////////////////////////////

		int	iChanVal = 255;
		source = XTInitTask (init_pattern, "dimensions", &m_iBlankWidth, &m_iBlankLength,
							"constant", &iChanVal, NULL,
								ARG_END);
	}
	iIndex = 0;
	if (!m_MergeFiles[iIndex].sFileName) return source;
	if (!source) {
//		if (!IS_DBL_EQUAL (m_MergeFiles[iIndex].dScale, 1.0)) {
//			source = 
//		} else
			source = XTSource (0, m_MergeFiles[iIndex].sFileName);

		if ((hdr = XTHeader (source))) 
		{
			getheaderfield (hdr, "Origin", "resolution", SP_DOUBLE, (char*)&dDPI);
			iForceResolution = (int)dDPI;
		}
		iFirstFile = false;
		if (m_MergeFiles[iIndex].iRotateDegrees)
			source = ApplyRotation (source, m_MergeFiles[iIndex].iRotateDegrees);
		iIndex++;
	}
	if (!source) return NULL;

	if (!m_MergeFiles[iIndex].sFileName) return source;

	primary = XTInitTask (init_nmerge, "link", source, ARG_END);
	while (primary && m_MergeFiles[iIndex].sFileName) {
		source = XTSource (0,m_MergeFiles[iIndex].sFileName);

		if (m_MergeFiles[iIndex].iRotateDegrees)
			source = ApplyRotation (source, m_MergeFiles[iIndex].iRotateDegrees);
		if (iFirstFile) {
			if ((hdr = XTHeader (source)))
			{
				getheaderfield (hdr, "Origin", "resolution", SP_DOUBLE, (char*)&dDPI);
				iForceResolution = (int)dDPI;
//	primary = ApplyResolution (primary,iForceResolution);	// testing 1.2.3, testing 1,2,3
			}
			iFirstFile = false;
		} else
			source = ApplyResolution (source, iForceResolution);

		if (source) {
			tt = XTInitTask (init_nmerge, "primary", primary, "x", &(m_MergeFiles[iIndex].iXoff),
							"y", &(m_MergeFiles[iIndex].iYoff), 
							"link", source,
							ARG_END);
			if (tt) primary = tt;
		}


		iIndex++;
	}
//	if (ExportSettings.iResolution <= 0)
//		ExportSettings.iResolution = iForceResolution;

	return primary;
}

  // Initialize a blank image as the main source
CImgPipe::Blank (int iRes, int iWidth, int iLength, int iBits)
{
	m_bBlank = true;
	m_iBlankWidth = iWidth * iRes;
	m_iBlankLength = iLength * iRes;
	m_iBlankBits = iBits;
	return true;
}

/*
	Specify a file to be merged into a CImgPipe's input,
	 and give it's location, rotation, and transparency.
*/
bool CImgPipe::NMerge (_TCHAR *sFilename, int iRotateDegrees, int iXoff, int iYoff, bool bTransparent, double dScale)
{
	int	iIndex = 0;

	while (m_MergeFiles[iIndex].sFileName) iIndex++;
	if (iIndex >= IP_MAX_MERGE-1) return false;

	m_MergeFiles[iIndex].sFileName = _tcsdup(sFilename);	// Fill in info for this list.
	m_MergeFiles[iIndex].iRotateDegrees = iRotateDegrees;
	m_MergeFiles[iIndex].iXoff = iXoff;
	m_MergeFiles[iIndex].iYoff = iYoff;
	m_MergeFiles[iIndex].bTransparent = bTransparent;
	m_MergeFiles[iIndex].dScale = dScale;
	m_MergeFiles[iIndex+1].sFileName = NULL;		// Mark the End of the List
	return true;
}

typedef struct {
	Instance	*task;
	BYTE		*bpBuffer;
	int			iWriteLine;			// Filling point
	int			iReadLine;			// Reading point
#ifdef PIPE_THREAD
	int			iScanLines, iPitch;
	int			iBufferLines;		// Total # of lines allocated in the buffer
	int			iKeepLines;			// Don't destroy this many lines!
	BOOL		bDead;				// Flag that thread is dead.
	BOOL		bDie;				// Flag to kill thread
	HANDLE		evDieOrGrow;
//	HANDLE		hWriteSourcePipe;
#endif	// PIPE_THREAD
} PIPE_PACKET;

#define	EDGE			92		// On a scale of 0-255, what defines an edge?
#define	CLOSE			8		// What defines close colors.
typedef unsigned char * SAMP;

#ifdef PIPE_THREAD
UINT __stdcall	PipesourceThreadFun( LPVOID pParam );
#	define	BUFFER_LINES	256			// # of lines that the pipe should be able to hold in it's buffer
#else
#	define	BUFFER_LINES	2			// # of lines that the pipe should be able to hold in it's buffer
#endif // PIPE_THREAD

/*
	CImgPipe::Calculate_AutomaticLossAdjustment (bool bCalculateBestCompression, IP_COMPRESSION *piCompression)

	Analysis of the image is as follows:

		Edgy images == lower loss level.
	Returns an integer percentage from 0-100 on how much loss is acceptable.

  Parameters:
	bCalculateBestCompression - if true, also find the best form of compression for this image.
  Uses:
	iALAlevel - 0-10 specifies how long to spend determining these things.
*/

#ifdef XTIP_PROJECT
int CImgPipe::Calculate_AutomaticLossAdjustment (bool bCalculateBestCompression, IP_COMPRESSION *piCompression, FILE *fResults)
#else
int CImgPipe::Calculate_AutomaticLossAdjustment (bool bCalculateBestCompression, IP_COMPRESSION *piCompression)
#endif
{
	Instance		*task, *insTemp;
	int				iLine, iPixels, iScanlines, iPitch, ipSamples[8];
	int				iPrevLine, iLookLines, iToldLookLines;
	unsigned long	uEdgeSamples, uCloseSamples, uIdenticalSamples, uDivisor;
	int				iEdgePercentage, iClosePercentage, iIdenticalPercentage, iLossOK;
	int				iBlankLines;
	unsigned char	*ucBuffer;
	register int	i;
	register SAMP	pSCur, pSCurinc, pSPrev;
	register long	A,B,C;
	int				ipBits[8], iBits;		// Set to Max # of channels + 1
	HEADER			*hdr;
	PIPE_PACKET		Packet;
	BOOL			bGrew = FALSE, bGrown = FALSE;

	if (!(task = BeginSource ())) return FALSE;

				// Investigate the header and see if we really need to process this file.
	hdr = XTHeader (task);
	getheaderimagebits (hdr, &ipBits[0]);
	getheaderparts (hdr, &ipSamples[0]);
	for (i=0, iBits=0; i < ipSamples[0]; iBits += ipBits[i++]);
	if (iBits < 8) {
		// Rules :
		//   for < 16 bits best compression is PackBits
		//
		if (bCalculateBestCompression) {	// why not use the original format?
			if (iBits == 1) *piCompression = COMP_G42D;
			else *piCompression = COMP_PACKBITS;
			XTEnd (task);
			return 0;
		} else {
			XTEnd (task);
			return 0;		// Minimal loss for these types of images.
		}
	}

			// Apply any resolution change to get an accurate reading.
	if (ExportSettings.iResolution > 0) {
		insTemp = ApplyResolution (task, ExportSettings.iResolution, iBits);
		if (insTemp) task = insTemp;
	}
					// Make sure that we are reading in RGB format
	task = XTInitTask (init_cspace, "link", task, "space", "rgbLinear", ARG_END);

					// Make sure that we are reading 8 bits per sample, pixel interleaved
	ipBits[0] = 8;		ipBits[1] = 0;
	task = XTInitTask (init_convert, "link", task, "bits", ipBits, "interleave", "pixel", ARG_END);

	hdr = XTHeader (task);
	getheaderdimensions (hdr, &iPixels, &iScanlines);
	getheadertotalbytes (hdr, &iPitch);
	getheaderparts (hdr, &ipSamples[0]);
	if (iPixels < 1) {
		XTEnd (task);
		return 0;
	}

//	SECURITY_ATTRIBUTES SecurityDescriptor;
//	SecurityDescriptor.nLength = sizeof (SecurityDescriptor);
//	SecurityDescriptor.lpSecurityDescriptor = NULL;
//	SecurityDescriptor.bInheritHandle = TRUE;
//	CreatePipe (&m_hReadSourcePipe, &m_hWriteSourcePipe, &SecurityDescriptor, iPitch * BUFFER_LINES);
//	Packet.hWriteSourcePipe = m_hWriteSourcePipe;

#define	MIN_LOOK_LINES	100		// For small files, don't reduce ALA to nothing!
	iBlankLines = 0;
	iLookLines = iScanlines;
	if (ExportSettings.jpegSettings.bAutoLossAdjustment) {
	//	ExportSettings.iALAlevel // - look at this value to determine how long to spend analyzing.
		iLookLines *= (ExportSettings.jpegSettings.iALAlevel);
		iLookLines /= (10);
		if (iLookLines < MIN_LOOK_LINES) iLookLines = min (MIN_LOOK_LINES, iScanlines);
	}

	Packet.iWriteLine = Packet.iReadLine = 0;	// Do our own piping (not using CreatePipe());
	ucBuffer = Packet.bpBuffer = new unsigned char[iPitch * BUFFER_LINES];
#ifdef PIPE_THREAD
	Packet.task = task;
	Packet.iScanLines = iLookLines;
	Packet.iPitch = iPitch;
	Packet.iBufferLines = BUFFER_LINES;
	Packet.iKeepLines = 2;
	Packet.bDie = false;
	Packet.bDead = false;
	Packet.evDieOrGrow = CreateEvent(NULL, 0, 0, NULL);	// Create an auto-reset event.

	_beginthreadex( NULL, 0, PipesourceThreadFun, (LPVOID)&Packet, 0, &m_threadHandle );
#endif	// PIPE_THREAD

		/*  Set a buffer to accomodate 3 lines */
	uEdgeSamples = uCloseSamples = uIdenticalSamples = 0;
	iEdgePercentage = 50;		// Default
	iClosePercentage = 0;
	iIdenticalPercentage = 50;
	if (ucBuffer) {
		iPrevLine = -1;
		iLine = 0;
GrewOut:
		iToldLookLines = iLookLines;
		for (; iLine < iToldLookLines; iLine++) {
			pSCur = ucBuffer+(Packet.iReadLine*iPitch);

#ifndef PIPE_THREAD
			if (XTProcess (task, pSCur))
				break;
#else
//			ReadFile (m_hReadSourcePipe, pSCur, iPitch, &dwBytesRead, NULL);	// Read from input pipe
//	fprintf (stderr, "Read %d, Write %d\n", Packet.iReadLine, Packet.iWriteLine);	/* Wait for data */
//	WaitForSingleObject( Ocr_ThreadInfo.hOcrOkToProceed, INFINITE );
			while (Packet.iReadLine == Packet.iWriteLine /*&& iLine < iLookLines-1*/)
				Sleep (10);
#endif
									/* Now we can analyze the buffer for edges, etc. */
			if (iLine) {			// Check against the previous line(s) for an edge
				pSCurinc = pSCur + ipSamples[0];
				pSPrev = ucBuffer+(iPrevLine*iPitch);
				i = iPixels-1;
				while (i--) {
								/* NOTE!!!! - This code assumes running on an INTEL BYTE ORDER machine */
					A = *(long*)pSCur;
					pSCur += 3;
					B = *(long*)pSCurinc;
					pSCurinc += 3;
					C = *(long*)pSPrev;
					pSPrev += 3;

					B -= A;
					if ((B+0x202020)&0xC0C0C0) 
						uEdgeSamples++;		// EDGE of 32
					else if ((A-C+0x202020) & 0xC0C0C0) uEdgeSamples++;
					else if (!(B&0x00ffffff)) uIdenticalSamples++;
					else uCloseSamples++;
				}
					// Always look past the white space at the top of the image.
				if (!bGrown) {
					if (uIdenticalSamples == (unsigned)((iPixels-1)*(iLine)) && iLookLines<iScanlines) {
						iLookLines++;
						iBlankLines++;
						bGrew = TRUE;
#ifdef PIPE_THREAD   // For PIPE_THREAD, Synch with the feed thread.
						Packet.iScanLines += 1;		// Keep the reading thread going
#endif // PIPE_THREAD
					} else {
						bGrown = TRUE;
						iToldLookLines = iLookLines;
						if (bGrew) {
#ifdef PIPE_THREAD   // For PIPE_THREAD, Synch with the feed thread.
							SetEvent (Packet.evDieOrGrow);
#endif // PIPE_THREAD
							bGrew = FALSE;
						}
					}
				}
			}
			if (++(Packet.iReadLine) >= BUFFER_LINES) Packet.iReadLine = 0;
			if (++iPrevLine >= BUFFER_LINES) iPrevLine = 0;
		}
		if (bGrew) {
#ifdef PIPE_THREAD   // For PIPE_THREAD, Synch with the feed thread.
			SetEvent (Packet.evDieOrGrow);
#endif // PIPE_THREAD
			bGrew = FALSE;
			goto GrewOut;
		}

#ifdef PIPE_THREAD
		Packet.bDie = true;		// Make sure input thread ends.
		SetEvent (Packet.evDieOrGrow);
#endif	// PIPE_THREAD

					// Reduce the identical sample count because of blank lines.
//		uIdenticalSamples -= (iPixels-1) * iBlankLines;
		uDivisor = max(1,((iLookLines*(iPixels-1)-uIdenticalSamples) / 100));
		iEdgePercentage = (uEdgeSamples / uDivisor);
		iClosePercentage = (uCloseSamples / uDivisor);
		iIdenticalPercentage = (uIdenticalSamples / (max(1,((iLookLines*(iPixels-1)) / 100))));
	}
	/* cleanup and release XTIP pipeline */
	XTEnd (task);
//	CloseHandle (m_hReadSourcePipe);
	if (Packet.bpBuffer) delete Packet.bpBuffer;

	if (bCalculateBestCompression) {
			// Calculate the best compression to use (assumes TIFF output format).
			//  PACKBITS - For images with a lot of the same values.
			//	JPEG_LOSSLESS,	- Best for lots of edges.
			//	JPEG_LOSSY,	- best for photos (smooth gradiations).
		if (iIdenticalPercentage > 66) 
			*piCompression = COMP_PACKBITS;
		else if (((float)iEdgePercentage / (float)iClosePercentage) > 0.09) 
			*piCompression = COMP_JPEG_LOSSLESS;
		else 
			*piCompression = COMP_JPEG_LOSSY;		
	}

		/* Returns a percentage from 0-100 on how much loss is acceptable. */
			// Edges as a percentage of 10% of the non-identical area

#ifdef PIPE_THREAD
	while (!Packet.bDead);
#endif // PIPE_THREAD

#ifdef XTIP_PROJECT
	if (fResults) {
		// CAREFUL OF /0
		fprintf (fResults, "    Edge: %d%%,  Close: %d%%,  (Identical: %d%%).\n", (iEdgePercentage), (iClosePercentage), iIdenticalPercentage);
	}
#endif
	// Straight line formula reduces the acceptable loss with more edges found.
	// y = Mx + C;
#define	M	 (3.568)			// (3.63636363636)
#define	C	 (-290)				// (-283.63636363636)
//	iLossOK = (int)(((iClosePercentage + (2*iIdenticalPercentage))*M) + C);
	iLossOK = 100-(5*iEdgePercentage);
	if (iLossOK < 0) iLossOK = 0;
	return min (100,iLossOK);
}


#ifdef PIPE_THREAD
/*
	This thread runs XTIP and places all of it's output into the pipe described by the Packet parameter.
	This is so that the file reading will be in one pipe, and the actual XTIP processing will occur in a
		seperate thread.  The idea behind this is that hopefully the other process can be running while
		this one is waiting for DMA input from disc or network.
*/
UINT __stdcall PipesourceThreadFun( LPVOID pParam )
{
	PIPE_PACKET *	Packet = (PIPE_PACKET*) pParam;
//	DWORD			dwBytesWritten;
	int				iLine, iReadpoint, iScanLines;
	unsigned char *	ucBuffer;
	bool			bFailed = false;

	if (!Packet->bpBuffer) return FALSE;
	iLine = 0;
	do {
		iScanLines = Packet->iScanLines;
		for (; iLine < iScanLines; iLine++) {
ptfSync:
			if (Packet->bDie) break;		// Die at THE END.
			iReadpoint = Packet->iReadLine - Packet->iKeepLines;
			if (iReadpoint < 0) iReadpoint += BUFFER_LINES;
			if (Packet->iWriteLine == iReadpoint-1) {
				Sleep(10);
				goto ptfSync;
			}
			ucBuffer = Packet->bpBuffer + (Packet->iWriteLine * Packet->iPitch);
			if (!bFailed) bFailed = XTProcess (Packet->task, ucBuffer);
//			WriteFile (Packet->hWriteSourcePipe, ucBuffer, Packet->iPitch, &dwBytesWritten, NULL);
			if (++(Packet->iWriteLine) >= BUFFER_LINES) Packet->iWriteLine = 0;
		}
		WaitForSingleObject( Packet->evDieOrGrow, INFINITE );
	} while (iLine < Packet->iScanLines && !Packet->bDie);
	Packet->bDead = TRUE;
//	CloseHandle (Packet->hWriteSourcePipe);
//	AfxEndThread( 0 );
	return TRUE;
}
#endif	// PIPE_THREAD


/*
BOOL CImgPipe::Render (int iW, int iH,unsigned char *ucpImagebuf, int iPitch);

	Writes the image to memory at a specified size (iW,iH).

	int iW,iH;
		Size of the output representation
	usigned char *ucpImagebuf;
		byte pointer to place the input into
	int iPitch;
		number of bytes per line of the destination bitmap

  Return Value:
		TRUE on success, FALSE on failure
*/
BOOL CImgPipe::Render (int iW, int iH, unsigned char *ucpImagebuf, int iPitch)
{
	int				iPixels, iScanlines;
	HEADER			*hdr;
	Instance		*insTemp;
	int				iBits;

	if (!(m_task = XTInitTask (init_readimage,"file",m_sInFileName,"scale",&iW,&iH,ARG_END) )) {
		error->set (ERIS);
		return FALSE;
	}

	insTemp = ApplyConversions (m_task);		// Apply any extra conversions
	if (insTemp) m_task = insTemp;

	hdr = XTHeader (m_task);
	iBits = getheaderbitsperpixel (hdr);

	if (iBits > 8) {			// Make sure that we are reading 8 bits per sample
		insTemp = XTInitTask (init_channel,"link",m_task,"parts","bgr",ARG_END);
		if (insTemp) m_task = insTemp;

		insTemp = XTInitTask (init_convert, "link", m_task, "interleave", "pixel", ARG_END);
		if (insTemp) m_task = insTemp;
	}

	hdr = XTHeader (m_task);
	getheaderdimensions (hdr, &iPixels, &iScanlines);

	iScanlines = min (iScanlines, iH);
	while (iScanlines--) {
		if (XTProcess (m_task, ucpImagebuf)) return FALSE;
		ucpImagebuf += iPitch;
	}
	return TRUE;
}


//////////////////////////////////////////////  IPAM Functions ///////////////////////////////////
/*
	ConvertToJpeg
*/
int	CImgPipe::ConvertToJPEG (LPCTSTR sInFile, LPCTSTR sOutFile)
{
	char	command[(_MAX_PATH*2)+64];

	sprintf (command, "Pipeline12 -src \"%s\" -photo srgb -angle 0 -res 75 75 -output \"%s\"", sInFile, sOutFile);
	return RunIPAM (command);
}

/*
	ConvertToTIFF
*/
int	CImgPipe::ConvertToG4TIFF (LPCTSTR sInFile, LPCTSTR sOutFile)
{
	char	command[(_MAX_PATH*2)+64];

	sprintf (command, "Pipeline11 -src \"%s\" -output \"%s\"", sInFile, sOutFile);
	return RunIPAM (command);
}

/*
	RunIPAM
*/
int CImgPipe::RunIPAM (char *command)
{
	IPAM		*ipam;
	int			i, nIns, err;
	Instance	*ins[10];

	ipam=InitializeIPAccess ();

	err = DpIPAccess (ipam, command, NULL, NULL, 0, ins, &nIns);
	if (nIns == 0) XTAbort();

	for (i=0; i < min (1, nIns); i++ )
	{
		if (ins[i] == NULL) XTAbort();
#if 0
		if (XTProcessImage (ins[i], (i==0)?1:-1) != XTNOERROR) XTAbort ();
#else
	unsigned char *buf;
	int				pix, lin, tbytes;
	HEADER *hdr = XTHeader(ins[i]);

	getheaderdimensions(hdr, &pix, &lin);
	getheadertotalbytes(hdr, &tbytes);
	buf = (unsigned char*)calloc(tbytes, sizeof(unsigned char));
	for (int j=0; j<lin; ++j)
		{
		XTProcess(ins[i], buf);
		}
	XTEnd(ins[i]);
#endif
	}

	ReleaseIPAccess (ipam);
	return TRUE;
}

CImgPipe::RunPipeline2 (LPCTSTR sOutFile)
{
	char	*cpSpace = NULL;	// NOT _TCHAR !
	char	command[(_MAX_PATH*2)+64];

	sprintf (command, "Pipeline2 -src \"%s\"", m_sInFileName);
	switch (ExportSettings.iColorSpace()) {
		case CSPACE_YCBCR:
			cpSpace = "YCbCr";
			break;
		case CSPACE_CMYK:
			cpSpace = "cmykLinear";
			break;
		case CSPACE_LAB:
			cpSpace = "CIELAB";
			break;
		case CSPACE_GRAY:
			cpSpace = "grayLinear";
			break;
		case CSPACE_RGB:
			cpSpace = "srgb";
			break;
	}
	if (cpSpace) sprintf (command+strlen(command), " -photo %s", cpSpace);

	sprintf (command+strlen(command), " -output \"%s\"", m_sInFileName);
	return RunIPAM (command);
}

/*
	Reads a word stored in the Motorola byte order from an input stream.
	Works on either Intel or Motorola platform
*/
WORD Motorola_Word ( FILE *fp )
{
	WORD	w,a,b;

	a = getc (fp);
	b = getc (fp);
	w = (b&0xff) << 8;
	w |= (a & 0xff);
	return w;
}

#define	FIELD_BYTE		1
#define	FIELD_ASCII		2
#define	FIELD_SHORT		3
#define	FIELD_LONG		4
#define	FIELD_RATIONAL	5

#define	PHT_GRAY	1
#define	PHT_RGB		2
#define	PHT_INDEXED	3
#define	PHT_CMYK	5
#define	PHT_YCC		6
#define	PHT_LAB		8

#define	TAG_NEW_SUBFILETYPE				0xFE
#define	TAG_IMAGE_WIDTH					0X100
#define	TAG_IMAGE_LENGTH				0X101
#define	TAG_BITS_PER_SAMPLE				0X102
#define	TAG_SAMPLES_PER_PIXEL			0X115
#define	TAG_COMPRESSION					0X103
#define	TAG_PHOTOMETRIC_INTERPRETATION	0X106
#define	TAG_STRIP_OFFSETS				0X111
#define	TAG_ROWS_PER_STRIP				0X116
#define	TAG_STRIP_BYTE_COUNTS			0X117
#define	TAG_XRESOLUTION					0X11A
#define	TAG_YRESOLUTION					0X11B
#define	TAG_RESOLUTION_UNIT				0X128

#define	TAG_JPEG_PROC				0X200
#define	TAG_JPEG_JFIF				0X201
#define	TAG_JPEG_JFIF_LENGTH		0X202
#define	TAG_JPEG_RESTART_INTERVAL	0X203
#define	TAG_JPEG_LOSSLESS_PREDCITOR	0X205
#define	TAG_JPEG_POINT_TRANSFORMS	0X206
#define	TAG_JPEG_QTABLES			0X207		// LOSSY Q TABLES.
#define	TAG_JPEG_DCTABLES			0X208		// LOSSLESS HUFFMAN TABLES.
#define	TAG_JPEG_ACTABLES			0X209		// LOSSY HUFFMAN TABLES.

static void Iputw (WORD w, FILE *fp);
static void Iputl (DWORD dw, FILE *fp);
/* Write out a word in intel byte format */
static void Iputw (WORD w, FILE *fp)
{
	putc (w&0xff, fp);
	putc (w>>8, fp);
}

static void Iputl (DWORD dw, FILE *fp)
{
	Iputw ((WORD)(dw & 0xffff), fp);
	Iputw ((WORD)(dw >>16), fp);
}

static void WriteTag (FILE *fp, int iTag, int iFieldType, int iCount, int iValue, int iValue2=0);
static void WriteTag (FILE *fp, int iTag, int iFieldType, int iCount, int iValue, int iValue2)
{
	int	iFieldLength;

	Iputw (iTag, fp);
	Iputw (iFieldType, fp);
	Iputl (iCount, fp);				// Long
	switch (iFieldType) {
		case	FIELD_BYTE:
			iFieldLength = 1;
			break;
		case	FIELD_ASCII:
			iFieldLength = 1;
			break;
		case	FIELD_SHORT:
			iFieldLength = 2;
			break;
		case	FIELD_LONG:
			iFieldLength = 4;
			break;
		case	FIELD_RATIONAL:
			iFieldLength = 8;
			break;
	}
	if (iFieldLength * iCount <= 4) {		// Value will fit in 4 bytes right here.
		switch (iFieldType) {
			case	FIELD_BYTE:
				iFieldLength = 1;
				break;
			case	FIELD_ASCII:
				iFieldLength = 1;
				break;
			case	FIELD_SHORT:
				Iputw (iValue, fp);
				if (iCount == 2) Iputw (iValue2, fp); else Iputw (0, fp);
				break;
			case	FIELD_LONG:
				Iputl (iValue, fp);
				break;
		}
	} else {
		Iputl (iValue, fp);		// PUT IN THE OFFSET
	}

}


/*
CImgPipe::Make_JPEG_TIFF (LPCTSTR sJPEGFilename, LPCTSTR sTIFFFilename,int iWidth,int iLength,int iDPI);

  Builds a .Tiff header for JPEG file format and then tacks on the JPEG file 
  Makes a TIFF file with JPEG storage compatible with the TIFF 6.0 Spec.

	RETURN VALUE:
		FALSE : Failure
		 TRUE : Success
*/
BOOL CImgPipe::Make_JPEG_TIFF (LPCTSTR sJPEGFilename, LPCTSTR sTIFFFilename,int iWidth,int iLength,int iDPI)
{
	int				i, iJOffset = 0, iMarkLength;
	unsigned char	ucMarker;
	FILE			*sfp, *dfp;
	long			alQOffsets[64], iQCount = 0;		// Quantization tables
	long			alHOffsets[64], iHCount = 0;		// Huffman tables
	long			iNextData, iEndData;
	unsigned char	*buf;
	int				iSamplesPerPixel = 3;
	int				iPht;
	BOOL			bRval = TRUE;

	if (!(sfp = _tfopen (sJPEGFilename, "rb"))) return FALSE;

	fseek (sfp, 0, SEEK_END);
	if (getDiskFree(sTIFFFilename) < 768 + ftell(sfp)) {
		error->set (ENODISK);
		fclose (sfp);
		return FALSE;
	}
	rewind (sfp);

	if (!(dfp = _tfopen (sTIFFFilename, "wb"))) {
		error->set (EDSTACS);
		fclose (sfp);
		return FALSE;
	}

	Iputw (0x4949, dfp);				// Intel byte order
	putc (42, dfp);	putc (0, dfp);		// Tiff
	putc (0x30, dfp); putc (0, dfp);	// 0x30 = offset of first IFD entry
	Iputw (0, dfp);						//    is long word.

	// Now write 0x28 bytes of description from this file

	fprintf (dfp, "%40s", "Created by XEROX image services");

int	TAG_COUNT = 18;
	if (ExportSettings.iOutputCompression() == COMP_JPEG_LOSSLESS) TAG_COUNT--;	// Lossless has 1 less field

	Iputw (TAG_COUNT, dfp);

	WriteTag (dfp, TAG_NEW_SUBFILETYPE, FIELD_LONG, 1, 0);			// JPEG Compression (6)
	WriteTag (dfp, TAG_COMPRESSION, FIELD_SHORT, 1, 6);				// JPEG Compression (6)
	WriteTag (dfp, TAG_IMAGE_WIDTH, FIELD_SHORT, 1, iWidth);
	WriteTag (dfp, TAG_IMAGE_LENGTH, FIELD_SHORT, 1, iLength);
	WriteTag (dfp, TAG_ROWS_PER_STRIP, FIELD_SHORT, 1, iLength);

	iPht = PHT_RGB;
	switch (ExportSettings.iColorSpace()) {
		case CSPACE_YCBCR:
			iPht = PHT_YCC;
			break;
		case CSPACE_CMYK:
			iPht = PHT_CMYK;
			break;
		case CSPACE_LAB:
//			iPht = PHT_LAB;
			iPht = PHT_YCC;
			break;
		case CSPACE_GRAY:
			iPht = PHT_GRAY;
			break;
		case CSPACE_INDEXED_RGB:
			iPht = PHT_INDEXED;
			break;
		case CSPACE_RGB:
			iPht = PHT_RGB;
			break;
	}
	WriteTag (dfp, TAG_PHOTOMETRIC_INTERPRETATION, FIELD_SHORT, 1, iPht);  // 
	WriteTag (dfp, TAG_SAMPLES_PER_PIXEL, FIELD_SHORT, 1, iSamplesPerPixel);

	while (fgetc (sfp) == 0xff) {		// Read the JPEG header.
		ucMarker = fgetc (sfp);
		iJOffset += 2;
		if (ucMarker == 0xD8) continue;		// JPEG identifier
		if (ucMarker == 0xD9) break;		// EOI (End of Image) marker

		iMarkLength = Motorola_Word (sfp);
		switch (ucMarker) {
			case 0xE0:			// JFIF
				break;
			case 0xDB:			// Quantization Table Marker
				alQOffsets[iQCount++] = iJOffset;// Save up these locations and write a single tag to list them.
				break;
			case 0xC4:			// Huffman DC Table Marker
				alHOffsets[iHCount++] = iJOffset;// Save up these locations and write a single tag to list them.
				break;
			case 0xC0:			// Start of Frame Marker
				break;
			case 0xDA:			// Start of Scan Marker
				break;
			case 0xFE:			// Comment Marker
				break;
		}
		iJOffset += iMarkLength;
		fseek (sfp, iMarkLength-2, SEEK_CUR);
	}

	iNextData = (TAG_COUNT * 12) + 4 + 0x32;
	iEndData = iNextData + 16 + (iHCount * 4);
	if (ExportSettings.iOutputCompression() == COMP_JPEG_LOSSY) iEndData += (iQCount * 4);

	if (iSamplesPerPixel == 1)
		WriteTag (dfp, TAG_BITS_PER_SAMPLE, FIELD_SHORT, 1, 8);
	else {
		WriteTag (dfp, TAG_BITS_PER_SAMPLE, FIELD_SHORT, iSamplesPerPixel, iNextData);
		iNextData += 8;
		iEndData += 8;
	}

	WriteTag (dfp, TAG_RESOLUTION_UNIT, FIELD_SHORT, 1, 2);		// Dots per inch
	WriteTag (dfp, TAG_XRESOLUTION, FIELD_RATIONAL, 1, iNextData);	// Dots per inch
	iNextData += 8;
	WriteTag (dfp, TAG_YRESOLUTION, FIELD_RATIONAL, 1, iNextData);	// Dots per inch
	iNextData += 8;

	WriteTag (dfp, TAG_JPEG_PROC, FIELD_SHORT, 1, ExportSettings.iOutputCompression()==COMP_JPEG_LOSSLESS?14:1);	// Baseline Process
	if (ExportSettings.iOutputCompression() == COMP_JPEG_LOSSLESS) 
	{
		WriteTag (dfp, TAG_JPEG_DCTABLES, FIELD_LONG, iHCount, iNextData);
		iNextData += iHCount * 4;
	} else {
		WriteTag (dfp, TAG_JPEG_ACTABLES, FIELD_LONG, iHCount, iNextData);
		iNextData += iHCount * 4;
		WriteTag (dfp, TAG_JPEG_QTABLES, FIELD_LONG, iQCount, iNextData);
		iNextData += iQCount * 4;
	}

	// iJOffset now contains the offset of the start of actual JPEG Data.
	WriteTag (dfp, TAG_STRIP_OFFSETS, FIELD_LONG, 1, iJOffset+iNextData);
	fseek (sfp, 0, SEEK_END);
	WriteTag (dfp, TAG_STRIP_BYTE_COUNTS, FIELD_LONG, 1, ftell(sfp)-iJOffset);

	WriteTag (dfp, TAG_JPEG_JFIF, FIELD_LONG, 1, iEndData);					// Point to SOI
	WriteTag (dfp, TAG_JPEG_JFIF_LENGTH, FIELD_LONG, 1, ftell(sfp));

	Iputl (0, dfp);		// Write out 4 zeros after the last IFD TAG


	//**************************** Now write out the Data *********************************
	if (iSamplesPerPixel > 1) {
		Iputw (8,dfp);		Iputw (8,dfp);		Iputw (8,dfp);		Iputw (8,dfp);
	}
	// xres, yres (RATIONALS)
	Iputl (iDPI,dfp);	 Iputl (1,dfp);		// Numerator, Denominator
	Iputl (iDPI,dfp);	 Iputl (1,dfp);		// Numerator, Denominator
	// DC table
	for (i=0; i<iHCount; i++) Iputl (alHOffsets[i]+iEndData, dfp);
	if (ExportSettings.iOutputCompression() == COMP_JPEG_LOSSY)
		for (i=0; i<iQCount; i++) Iputl (alQOffsets[i]+iEndData, dfp);
	// Now, append the JPEG file to the TIFF
#define	BUFSIZE	512
	buf = new unsigned char[BUFSIZE];
	if (buf) {
		int	count;

		fseek (sfp, 0, SEEK_SET);
		while ((count = fread (buf, 1, BUFSIZE, sfp))) {
			if(fwrite (buf, 1, count, dfp) != (size_t)count) {
				error->set (EIOWR);
				bRval = FALSE;
				break;
			}
		}
		delete buf;
	} else {
		error->set (ENOMEM);
		bRval = FALSE;
	}
	fclose (dfp);
	fclose (sfp);
	return bRval;
}

static _TCHAR * IP_COLORSPACE_STRINGS[12];
static _TCHAR * IP_COMPRESSION_STRINGS[12];

static int IP_COLORSPACE_STRING_IDS[] = {
	IDS_COLORSPACE_ORIGINAL,
	IDS_COLORSPACE_RGB,
	IDS_COLORSPACE_YCBCR,
	IDS_COLORSPACE_CMYK,
	IDS_COLORSPACE_LAB,
	IDS_COLORSPACE_GRAYSCALE,
	IDS_COLORSPACE_INDEXED_RGB,
	0
};

static int IP_COMPRESSION_STRING_IDS[] = {
	IDS_COMPRESSION_OPTIMAL,
	IDS_COMPRESSION_GROUP4,
	IDS_COMPRESSION_JPEG_LOSSLESS,
	IDS_COMPRESSION_JPEG_LOSSY,
	IDS_COMPRESSION_PACKBITS,
	IDS_COMPRESSION_UNCOMPRESSED,
	0
};

HINSTANCE	l_hInst;

BOOL APIENTRY DllMain( HANDLE hModule, DWORD ul_reason, LPVOID lpReserved )
{
	int		iIndex;
	char	szHolder[256];

	switch ( ul_reason )
		{
		case DLL_PROCESS_ATTACH:
		case DLL_THREAD_ATTACH:
		case DLL_THREAD_DETACH:
		case DLL_PROCESS_DETACH:
		break;
		}

	l_hInst = (HINSTANCE) hModule;
	iIndex=0;
	while (IP_COLORSPACE_STRING_IDS[iIndex]) {
		LoadString (l_hInst, IP_COLORSPACE_STRING_IDS[iIndex], szHolder, 255);
		IP_COLORSPACE_STRINGS[iIndex++] = _tcsdup (szHolder);
	}
	IP_COLORSPACE_STRINGS[iIndex] = NULL;

	iIndex=0;
	while (IP_COMPRESSION_STRING_IDS[iIndex]) {
		LoadString (l_hInst, IP_COMPRESSION_STRING_IDS[iIndex], szHolder, 255);
		IP_COMPRESSION_STRINGS[iIndex++] = _tcsdup (szHolder);
	}
	IP_COMPRESSION_STRINGS[iIndex] = NULL;
	return TRUE;
}


_TCHAR *IP_EXPORT_SETTINGS::ExpGetColorspaceString (int iIndex)
{
	return IP_COLORSPACE_STRINGS[iIndex];
}
_TCHAR *IP_EXPORT_SETTINGS::ExpGetCompressionString (int iIndex)
{
	return IP_COMPRESSION_STRINGS[iIndex];
}

IP_COLOR_SPACE		IP_EXPORT_SETTINGS::iColorSpace()
{ 
	return (IP_COLOR_SPACE)Lookup (IP_COLORSPACE_STRINGS, sColorSpace); 
}

IP_COMPRESSION		IP_EXPORT_SETTINGS::iOutputCompression() 
{ 
	return (IP_COMPRESSION)Lookup (IP_COMPRESSION_STRINGS, sOutputCompression); 
}

bool	IP_EXPORT_SETTINGS::SetColorSpace (IP_COLOR_SPACE ipcs)
{
	_tcscpy (sColorSpace, ExpGetColorspaceString ((int)ipcs));
	return TRUE;
}

bool	IP_EXPORT_SETTINGS::SetCompression (IP_COMPRESSION ipcmp)
{
	_tcscpy (sOutputCompression, ExpGetCompressionString ((int)ipcmp));
	return TRUE;
}

IP_EXPORT_SETTINGS::IP_EXPORT_SETTINGS()
{
	IP_JPEG_SETTINGS	ijs = { 87, 0, 1, 4 };		// Default JPEG Settings

	jpegSettings = ijs;
	iBitsPerPixel = 0;					// output Bits per pixel (0=Automatic)
	iResolution = 0;					// Use original
	iWidth = iHeight = 0;				// Use original
	_tcscpy (sColorSpace, IP_COLORSPACE_STRINGS[CSPACE_AUTOMATIC]);			// Color Space
	_tcscpy (sOutputCompression, IP_COMPRESSION_STRINGS[COMP_AUTOMATIC]);	// Compression

	bAlpha = 0;							// Alpha opacity channel?
	bDither = 1;						// Dithering
	bCreateThumbnails = 0;
	bFuseImages = 0;
	dScale = 1.0;
	iRotateDegrees = 0;
	szColorProfile = NULL;
};


#endif // #if 0




