#
#WINDOWSMakefile
#
#ThisistheVisualStudioMakefileforBFC
#
#Copyright(C)2004through2008byWilliamP.Foster,allrightsreserved
#
#
# Generated via Programmer, a programmer's utility.
#
DebugDir=Debug
ReleaseDir=Release

ALL_H = Array2d.h BFCDefs.h BFCDefs_KeyDefs.h BFCTypes.h  \
		BFCUnDefs.h Bfc_DebugStatic.h bfc_unix.h bfc_windows.h  \
		CBfc_2dRect.h CBfc_2dShape.h CBfc_2dSize.h CBfc_Angle.h  \
		CBfc_Array.h CBfc_CompressionAlgorythm.h CBfc_Distance.h CBfc_DynamicLink.h  \
		CBfc_Exception.h CBfc_File.h CBfc_Filename.h CBfc_LinkedList.h  \
		CBfc_Map2d.h CBfc_Matrix.h CBfc_Object.h CBfc_PointSpace3d.h  \
		CBfc_PointSpaceTime.h CBfc_PointTime.h CBfc_Range2d.h CBfc_ReferencedAllocation.h  \
		CBfc_ReferencedObject.h CBfc_ReferencedPointer.h CBfc_ReferencedValue.h CBfc_Registry.h  \
		CBfc_Stream.h CBfc_StreamSource.h CBfc_String.h CBfc_Tree.h  \
		CBfc_Value.h character.h speedfloat.h  

ALL_CPP = ../src\Bfc_DebugStatic.cpp ../src\CBfc_2dRect.cpp ../src\CBfc_2dSize.cpp ../src\CBfc_Angle.cpp  \
		../src\CBfc_Array.cpp ../src\CBfc_CompressionAlgorythm.cpp ../src\CBfc_Distance.cpp ../src\CBfc_DynamicLink.cpp  \
		../src\CBfc_Exception.cpp ../src\CBfc_File.cpp ../src\CBfc_Filename.cpp ../src\CBfc_LinkedList.cpp  \
		../src\CBfc_MatrixDoubles.cpp ../src\CBfc_PointSpace3d.cpp ../src\CBfc_PointSpaceTime.cpp ../src\CBfc_PointTime.cpp  \
		../src\CBfc_Range2d.cpp ../src\CBfc_ReferencedAllocation.cpp ../src\CBfc_ReferencedObject.cpp ../src\CBfc_ReferencedPointer.cpp  \
		../src\CBfc_Registry.cpp ../src\CBfc_Stream.cpp ../src\CBfc_StreamSource.cpp ../src\CBfc_String.cpp  \
		../src\CBfc_String8.cpp ../src\CBfc_Value.cpp ../src\character.cpp ../src\Rect2dU.cpp  \
		../src\Size2dU.cpp  

ALL_OBJ = ../src\Bfc_DebugStatic.o ../src\CBfc_2dRect.o ../src\CBfc_2dSize.o ../src\CBfc_Angle.o  \
		../src\CBfc_Array.o ../src\CBfc_CompressionAlgorythm.o ../src\CBfc_Distance.o ../src\CBfc_DynamicLink.o  \
		../src\CBfc_Exception.o ../src\CBfc_File.o ../src\CBfc_Filename.o ../src\CBfc_LinkedList.o  \
		../src\CBfc_MatrixDoubles.o ../src\CBfc_PointSpace3d.o ../src\CBfc_PointSpaceTime.o ../src\CBfc_PointTime.o  \
		../src\CBfc_Range2d.o ../src\CBfc_ReferencedAllocation.o ../src\CBfc_ReferencedObject.o ../src\CBfc_ReferencedPointer.o  \
		../src\CBfc_Registry.o ../src\CBfc_Stream.o ../src\CBfc_StreamSource.o ../src\CBfc_String.o  \
		../src\CBfc_String8.o ../src\CBfc_Value.o ../src\character.o ../src\Rect2dU.o  \
		../src\Size2dU.o  

ALL_DEBUG_OBJ = $(DebugDir)\Bfc_DebugStatic.o $(DebugDir)\CBfc_2dRect.o $(DebugDir)\CBfc_2dSize.o $(DebugDir)\CBfc_Angle.o  \
		$(DebugDir)\CBfc_Array.o $(DebugDir)\CBfc_CompressionAlgorythm.o $(DebugDir)\CBfc_Distance.o $(DebugDir)\CBfc_DynamicLink.o  \
		$(DebugDir)\CBfc_Exception.o $(DebugDir)\CBfc_File.o $(DebugDir)\CBfc_Filename.o $(DebugDir)\CBfc_LinkedList.o  \
		$(DebugDir)\CBfc_MatrixDoubles.o $(DebugDir)\CBfc_PointSpace3d.o $(DebugDir)\CBfc_PointSpaceTime.o $(DebugDir)\CBfc_PointTime.o  \
		$(DebugDir)\CBfc_Range2d.o $(DebugDir)\CBfc_ReferencedAllocation.o $(DebugDir)\CBfc_ReferencedObject.o $(DebugDir)\CBfc_ReferencedPointer.o  \
		$(DebugDir)\CBfc_Registry.o $(DebugDir)\CBfc_Stream.o $(DebugDir)\CBfc_StreamSource.o $(DebugDir)\CBfc_String.o  \
		$(DebugDir)\CBfc_String8.o $(DebugDir)\CBfc_Value.o $(DebugDir)\character.o $(DebugDir)\Rect2dU.o  \
		$(DebugDir)\Size2dU.o  

ALL_RELEASE_OBJ = $(ReleaseDir)\Bfc_DebugStatic.o $(ReleaseDir)\CBfc_2dRect.o $(ReleaseDir)\CBfc_2dSize.o $(ReleaseDir)\CBfc_Angle.o  \
		$(ReleaseDir)\CBfc_Array.o $(ReleaseDir)\CBfc_CompressionAlgorythm.o $(ReleaseDir)\CBfc_Distance.o $(ReleaseDir)\CBfc_DynamicLink.o  \
		$(ReleaseDir)\CBfc_Exception.o $(ReleaseDir)\CBfc_File.o $(ReleaseDir)\CBfc_Filename.o $(ReleaseDir)\CBfc_LinkedList.o  \
		$(ReleaseDir)\CBfc_MatrixDoubles.o $(ReleaseDir)\CBfc_PointSpace3d.o $(ReleaseDir)\CBfc_PointSpaceTime.o $(ReleaseDir)\CBfc_PointTime.o  \
		$(ReleaseDir)\CBfc_Range2d.o $(ReleaseDir)\CBfc_ReferencedAllocation.o $(ReleaseDir)\CBfc_ReferencedObject.o $(ReleaseDir)\CBfc_ReferencedPointer.o  \
		$(ReleaseDir)\CBfc_Registry.o $(ReleaseDir)\CBfc_Stream.o $(ReleaseDir)\CBfc_StreamSource.o $(ReleaseDir)\CBfc_String.o  \
		$(ReleaseDir)\CBfc_String8.o $(ReleaseDir)\CBfc_Value.o $(ReleaseDir)\character.o $(ReleaseDir)\Rect2dU.o  \
		$(ReleaseDir)\Size2dU.o  

LIBINSTALL=\Libraries

SHELL=C:/Windows/System32/cmd.exe
VER=1
srcdir=../src
includes=../../include

#LIBINSTALL is the Target!
LIBOUT = .

DEFS = -D WIN32

CCPP = cl
CPPDEBUG = -D _DEBUG /Zi
#INTELOPTIONS=-march=pentium3 -msse -mfpmath=sse
CPPFLAGS = $(INTELOPTIONS) -I$(srcdir) -I$(includes) /std:c++17 $(DEFS) -D BFC_STATICLIB

LINKER = lib
LINKEROPTIONS =
#LINKEROPTIONS = --export-dynamic

build: create debug

all : create check_headers debug release

backup:
	programmer -b .

rebuild: clean all

clean :
	del Debug\*.o
	del Release\*.o
	del $(LIBOUT)\BFC_d.lib
	del $(LIBOUT)\BFC.lib

head:
	programmer -h ../header src/*.cpp
	programmer -h ../header src/*.h

create:
	if NOT EXIST Debug (mkdir Debug)
	if NOT EXIST Release (mkdir Release)
	programmer -mpw $(srcdir)

debug : $(LIBOUT)/BFC_d.lib

$(LIBOUT)/BFC_d.lib : $(ALL_DEBUG_OBJ)
	$(LINKER) $(LINKEROPTIONS) /OUT:$(LIBOUT)/BFC_d.lib $(ALL_DEBUG_OBJ)

release : $(LIBOUT)/BFC.lib

$(LIBOUT)/BFC.lib : $(ALL_RELEASE_OBJ)
	$(LINKER) $(LINKEROPTIONS) /OUT:$(LIBOUT)/BFC.lib $(ALL_RELEASE_OBJ)

install: installd release
	copy $(LIBOUT)\BFC.lib $(LIBINSTALL)

installd: debug
	copy $(LIBOUT)\BFC_d.lib $(LIBINSTALL)

uninstall:
	del -f $(LIBINSTALL)\BFC.lib
	del -f $(LIBINSTALL)\BFC_d.lib

check_headers : $(ALL_H)
	$(CCPP) -E $(CPPFLAGS) ../include/BFC.h > junk




$(DebugDir)\Bfc_DebugStatic.o : ..\src\Bfc_DebugStatic.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\Bfc_DebugStatic.o ..\src\Bfc_DebugStatic.cpp

$(ReleaseDir)\Bfc_DebugStatic.o : ..\src\Bfc_DebugStatic.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\Bfc_DebugStatic.o ..\src\Bfc_DebugStatic.cpp

$(DebugDir)\CBfc_2dRect.o : ..\src\CBfc_2dRect.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_2dRect.o ..\src\CBfc_2dRect.cpp

$(ReleaseDir)\CBfc_2dRect.o : ..\src\CBfc_2dRect.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_2dRect.o ..\src\CBfc_2dRect.cpp

$(DebugDir)\CBfc_2dSize.o : ..\src\CBfc_2dSize.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_2dSize.o ..\src\CBfc_2dSize.cpp

$(ReleaseDir)\CBfc_2dSize.o : ..\src\CBfc_2dSize.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_2dSize.o ..\src\CBfc_2dSize.cpp

$(DebugDir)\CBfc_Angle.o : ..\src\CBfc_Angle.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_Angle.o ..\src\CBfc_Angle.cpp

$(ReleaseDir)\CBfc_Angle.o : ..\src\CBfc_Angle.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_Angle.o ..\src\CBfc_Angle.cpp

$(DebugDir)\CBfc_Array.o : ..\src\CBfc_Array.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_Array.o ..\src\CBfc_Array.cpp

$(ReleaseDir)\CBfc_Array.o : ..\src\CBfc_Array.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_Array.o ..\src\CBfc_Array.cpp

$(DebugDir)\CBfc_CompressionAlgorythm.o : ..\src\CBfc_CompressionAlgorythm.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_CompressionAlgorythm.o ..\src\CBfc_CompressionAlgorythm.cpp

$(ReleaseDir)\CBfc_CompressionAlgorythm.o : ..\src\CBfc_CompressionAlgorythm.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_CompressionAlgorythm.o ..\src\CBfc_CompressionAlgorythm.cpp

$(DebugDir)\CBfc_Distance.o : ..\src\CBfc_Distance.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_Distance.o ..\src\CBfc_Distance.cpp

$(ReleaseDir)\CBfc_Distance.o : ..\src\CBfc_Distance.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_Distance.o ..\src\CBfc_Distance.cpp

$(DebugDir)\CBfc_DynamicLink.o : ..\src\CBfc_DynamicLink.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_DynamicLink.o ..\src\CBfc_DynamicLink.cpp

$(ReleaseDir)\CBfc_DynamicLink.o : ..\src\CBfc_DynamicLink.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_DynamicLink.o ..\src\CBfc_DynamicLink.cpp

$(DebugDir)\CBfc_Exception.o : ..\src\CBfc_Exception.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_Exception.o ..\src\CBfc_Exception.cpp

$(ReleaseDir)\CBfc_Exception.o : ..\src\CBfc_Exception.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_Exception.o ..\src\CBfc_Exception.cpp

$(DebugDir)\CBfc_File.o : ..\src\CBfc_File.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_File.o ..\src\CBfc_File.cpp

$(ReleaseDir)\CBfc_File.o : ..\src\CBfc_File.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_File.o ..\src\CBfc_File.cpp

$(DebugDir)\CBfc_Filename.o : ..\src\CBfc_Filename.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_Filename.o ..\src\CBfc_Filename.cpp

$(ReleaseDir)\CBfc_Filename.o : ..\src\CBfc_Filename.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_Filename.o ..\src\CBfc_Filename.cpp

$(DebugDir)\CBfc_LinkedList.o : ..\src\CBfc_LinkedList.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_LinkedList.o ..\src\CBfc_LinkedList.cpp

$(ReleaseDir)\CBfc_LinkedList.o : ..\src\CBfc_LinkedList.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_LinkedList.o ..\src\CBfc_LinkedList.cpp

$(DebugDir)\CBfc_MatrixDoubles.o : ..\src\CBfc_MatrixDoubles.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_MatrixDoubles.o ..\src\CBfc_MatrixDoubles.cpp

$(ReleaseDir)\CBfc_MatrixDoubles.o : ..\src\CBfc_MatrixDoubles.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_MatrixDoubles.o ..\src\CBfc_MatrixDoubles.cpp

$(DebugDir)\CBfc_PointSpace3d.o : ..\src\CBfc_PointSpace3d.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_PointSpace3d.o ..\src\CBfc_PointSpace3d.cpp

$(ReleaseDir)\CBfc_PointSpace3d.o : ..\src\CBfc_PointSpace3d.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_PointSpace3d.o ..\src\CBfc_PointSpace3d.cpp

$(DebugDir)\CBfc_PointSpaceTime.o : ..\src\CBfc_PointSpaceTime.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_PointSpaceTime.o ..\src\CBfc_PointSpaceTime.cpp

$(ReleaseDir)\CBfc_PointSpaceTime.o : ..\src\CBfc_PointSpaceTime.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_PointSpaceTime.o ..\src\CBfc_PointSpaceTime.cpp

$(DebugDir)\CBfc_PointTime.o : ..\src\CBfc_PointTime.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_PointTime.o ..\src\CBfc_PointTime.cpp

$(ReleaseDir)\CBfc_PointTime.o : ..\src\CBfc_PointTime.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_PointTime.o ..\src\CBfc_PointTime.cpp

$(DebugDir)\CBfc_Range2d.o : ..\src\CBfc_Range2d.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_Range2d.o ..\src\CBfc_Range2d.cpp

$(ReleaseDir)\CBfc_Range2d.o : ..\src\CBfc_Range2d.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_Range2d.o ..\src\CBfc_Range2d.cpp

$(DebugDir)\CBfc_ReferencedAllocation.o : ..\src\CBfc_ReferencedAllocation.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_ReferencedAllocation.o ..\src\CBfc_ReferencedAllocation.cpp

$(ReleaseDir)\CBfc_ReferencedAllocation.o : ..\src\CBfc_ReferencedAllocation.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_ReferencedAllocation.o ..\src\CBfc_ReferencedAllocation.cpp

$(DebugDir)\CBfc_ReferencedObject.o : ..\src\CBfc_ReferencedObject.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_ReferencedObject.o ..\src\CBfc_ReferencedObject.cpp

$(ReleaseDir)\CBfc_ReferencedObject.o : ..\src\CBfc_ReferencedObject.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_ReferencedObject.o ..\src\CBfc_ReferencedObject.cpp

$(DebugDir)\CBfc_ReferencedPointer.o : ..\src\CBfc_ReferencedPointer.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_ReferencedPointer.o ..\src\CBfc_ReferencedPointer.cpp

$(ReleaseDir)\CBfc_ReferencedPointer.o : ..\src\CBfc_ReferencedPointer.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_ReferencedPointer.o ..\src\CBfc_ReferencedPointer.cpp

$(DebugDir)\CBfc_Registry.o : ..\src\CBfc_Registry.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_Registry.o ..\src\CBfc_Registry.cpp

$(ReleaseDir)\CBfc_Registry.o : ..\src\CBfc_Registry.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_Registry.o ..\src\CBfc_Registry.cpp

$(DebugDir)\CBfc_Stream.o : ..\src\CBfc_Stream.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_Stream.o ..\src\CBfc_Stream.cpp

$(ReleaseDir)\CBfc_Stream.o : ..\src\CBfc_Stream.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_Stream.o ..\src\CBfc_Stream.cpp

$(DebugDir)\CBfc_StreamSource.o : ..\src\CBfc_StreamSource.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_StreamSource.o ..\src\CBfc_StreamSource.cpp

$(ReleaseDir)\CBfc_StreamSource.o : ..\src\CBfc_StreamSource.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_StreamSource.o ..\src\CBfc_StreamSource.cpp

$(DebugDir)\CBfc_String.o : ..\src\CBfc_String.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_String.o ..\src\CBfc_String.cpp

$(ReleaseDir)\CBfc_String.o : ..\src\CBfc_String.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_String.o ..\src\CBfc_String.cpp

$(DebugDir)\CBfc_String8.o : ..\src\CBfc_String8.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_String8.o ..\src\CBfc_String8.cpp

$(ReleaseDir)\CBfc_String8.o : ..\src\CBfc_String8.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_String8.o ..\src\CBfc_String8.cpp

$(DebugDir)\CBfc_Value.o : ..\src\CBfc_Value.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\CBfc_Value.o ..\src\CBfc_Value.cpp

$(ReleaseDir)\CBfc_Value.o : ..\src\CBfc_Value.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\CBfc_Value.o ..\src\CBfc_Value.cpp

$(DebugDir)\character.o : ..\src\character.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\character.o ..\src\character.cpp

$(ReleaseDir)\character.o : ..\src\character.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\character.o ..\src\character.cpp

$(DebugDir)\Rect2dU.o : ..\src\Rect2dU.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\Rect2dU.o ..\src\Rect2dU.cpp

$(ReleaseDir)\Rect2dU.o : ..\src\Rect2dU.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\Rect2dU.o ..\src\Rect2dU.cpp

$(DebugDir)\Size2dU.o : ..\src\Size2dU.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /Fo$(DebugDir)\Size2dU.o ..\src\Size2dU.cpp

$(ReleaseDir)\Size2dU.o : ..\src\Size2dU.cpp 
		$(CCPP) -c $(CPPFLAGS) /Fo$(ReleaseDir)\Size2dU.o ..\src\Size2dU.cpp
