#
#WINDOWSMakefile
#
#ThisistheVisualStudioMakefileforBFC
#
#Copyright(C)2004through2008byWilliamP.Foster,allrightsreserved
#
#
# Generated via Programmer, a programmer's utility.
#

ALL_H = BFC.h BFCData.h BFCGUI.h BFCImage.h  \
		BFCLocal.h BFCOS.h BFCRIP.h BFCScript.h  \
		BFCUtil.h BFCVector.h Gears.h BFCDefs.h  \
		BFCDefs_KeyDefs.h BFCTypes.h BFCUnDefs.h Bfc_DebugStatic.h  \
		bfc_unix.h bfc_windows.h CBfc_2dRect.h CBfc_2dShape.h  \
		CBfc_2dSize.h CBfc_Angle.h CBfc_Array.h CBfc_CompressionAlgorythm.h  \
		CBfc_Distance.h CBfc_DynamicLink.h CBfc_Exception.h CBfc_File.h  \
		CBfc_Filename.h CBfc_LinkedList.h CBfc_Map2d.h CBfc_Matrix.h  \
		CBfc_Object.h CBfc_PointSpace3d.h CBfc_PointSpaceTime.h CBfc_PointTime.h  \
		CBfc_Range2d.h CBfc_ReferencedAllocation.h CBfc_ReferencedObject.h CBfc_ReferencedPointer.h  \
		CBfc_ReferencedValue.h CBfc_Registry.h CBfc_Stream.h CBfc_StreamSource.h  \
		CBfc_String.h CBfc_Tree.h CBfc_Value.h character.h  \
		speedfloat.h  

ALL_CPP = ../src\Bfc_DebugStatic.cpp ../src\CBfc_2dRect.cpp ../src\CBfc_2dSize.cpp ../src\CBfc_Angle.cpp  \
		../src\CBfc_Array.cpp ../src\CBfc_CompressionAlgorythm.cpp ../src\CBfc_Distance.cpp ../src\CBfc_DynamicLink.cpp  \
		../src\CBfc_Exception.cpp ../src\CBfc_File.cpp ../src\CBfc_Filename.cpp ../src\CBfc_LinkedList.cpp  \
		../src\CBfc_MatrixDoubles.cpp ../src\CBfc_PointSpace3d.cpp ../src\CBfc_PointSpaceTime.cpp ../src\CBfc_PointTime.cpp  \
		../src\CBfc_Range2d.cpp ../src\CBfc_ReferencedAllocation.cpp ../src\CBfc_ReferencedObject.cpp ../src\CBfc_ReferencedPointer.cpp  \
		../src\CBfc_Registry.cpp ../src\CBfc_Stream.cpp ../src\CBfc_StreamSource.cpp ../src\CBfc_String.cpp  \
		../src\CBfc_String8.cpp ../src\CBfc_Value.cpp ../src\character.cpp ../src\Rect2dU.cpp  \
		../src\Size2dU.cpp  

ALL_OBJ = ../src\Bfc_DebugStatic.o ../src\CBfc_2dRect.o ../src\CBfc_2dSize.o ../src\CBfc_Angle.o  \
		../src\CBfc_Array.o ../src\CBfc_CompressionAlgorythm.o ../src\CBfc_Distance.o ../src\CBfc_DynamicLink.o  \
		../src\CBfc_Exception.o ../src\CBfc_File.o ../src\CBfc_Filename.o ../src\CBfc_LinkedList.o  \
		../src\CBfc_MatrixDoubles.o ../src\CBfc_PointSpace3d.o ../src\CBfc_PointSpaceTime.o ../src\CBfc_PointTime.o  \
		../src\CBfc_Range2d.o ../src\CBfc_ReferencedAllocation.o ../src\CBfc_ReferencedObject.o ../src\CBfc_ReferencedPointer.o  \
		../src\CBfc_Registry.o ../src\CBfc_Stream.o ../src\CBfc_StreamSource.o ../src\CBfc_String.o  \
		../src\CBfc_String8.o ../src\CBfc_Value.o ../src\character.o ../src\Rect2dU.o  \
		../src\Size2dU.o  

ALL_DEBUG_OBJ = Debug\Bfc_DebugStatic.o Debug\CBfc_2dRect.o Debug\CBfc_2dSize.o Debug\CBfc_Angle.o  \
		Debug\CBfc_Array.o Debug\CBfc_CompressionAlgorythm.o Debug\CBfc_Distance.o Debug\CBfc_DynamicLink.o  \
		Debug\CBfc_Exception.o Debug\CBfc_File.o Debug\CBfc_Filename.o Debug\CBfc_LinkedList.o  \
		Debug\CBfc_MatrixDoubles.o Debug\CBfc_PointSpace3d.o Debug\CBfc_PointSpaceTime.o Debug\CBfc_PointTime.o  \
		Debug\CBfc_Range2d.o Debug\CBfc_ReferencedAllocation.o Debug\CBfc_ReferencedObject.o Debug\CBfc_ReferencedPointer.o  \
		Debug\CBfc_Registry.o Debug\CBfc_Stream.o Debug\CBfc_StreamSource.o Debug\CBfc_String.o  \
		Debug\CBfc_String8.o Debug\CBfc_Value.o Debug\character.o Debug\Rect2dU.o  \
		Debug\Size2dU.o  

ALL_RELEASE_OBJ = Release\Bfc_DebugStatic.o Release\CBfc_2dRect.o Release\CBfc_2dSize.o Release\CBfc_Angle.o  \
		Release\CBfc_Array.o Release\CBfc_CompressionAlgorythm.o Release\CBfc_Distance.o Release\CBfc_DynamicLink.o  \
		Release\CBfc_Exception.o Release\CBfc_File.o Release\CBfc_Filename.o Release\CBfc_LinkedList.o  \
		Release\CBfc_MatrixDoubles.o Release\CBfc_PointSpace3d.o Release\CBfc_PointSpaceTime.o Release\CBfc_PointTime.o  \
		Release\CBfc_Range2d.o Release\CBfc_ReferencedAllocation.o Release\CBfc_ReferencedObject.o Release\CBfc_ReferencedPointer.o  \
		Release\CBfc_Registry.o Release\CBfc_Stream.o Release\CBfc_StreamSource.o Release\CBfc_String.o  \
		Release\CBfc_String8.o Release\CBfc_Value.o Release\character.o Release\Rect2dU.o  \
		Release\Size2dU.o  

VER=1
srcdir=../src
includes=../../include

#LIBINSTALL is the Target!
LIBINSTALL=/lib

#LIBOUT is the intermediate folder
LIBOUT = \Users\Bill\Libraries

DEFS = -D WIN32

CCPP = cl
CPPDEBUG = -D _DEBUG /Zi
#INTELOPTIONS=-march=pentium3 -msse -mfpmath=sse
CPPFLAGS = $(INTELOPTIONS) -I$(srcdir) -I$(includes) $(DEFS) -D STATICLIB

LINKER = lib
LINKEROPTIONS =
#LINKEROPTIONS = --export-dynamic

build: create debug

all : create check_headers debug release

backup:
	programmer -b .

rebuild: clean all

clean :
	del Debug\*.o
	del Release\*.o
	del $(LIBOUT)\BFC_d.lib
	del $(LIBOUT)\BFC.lib

head:
	programmer -h ../header src/*.cpp
	programmer -h ../header src/*.h

create:
	rem mkdir Debug
	rem mkdir Release
	programmer -mpw $(srcdir)

debug : $(LIBOUT)/BFC_d.lib

$(LIBOUT)/BFC_d.lib : $(ALL_DEBUG_OBJ)
	rem g++ -shared -Wl,-soname,BFC_d.so.$(VER) -o $(LIBOUT)/BFC_d.so.$(VER) $(ALL_DEBUG_OBJ)
	$(LINKER) $(LINKEROPTIONS) /OUT:$(LIBOUT)/BFC_d.lib $(ALL_DEBUG_OBJ)

release : $(LIBOUT)/BFC.lib

$(LIBOUT)/BFC.lib : $(ALL_RELEASE_OBJ)
	rem g++ -shared -Wl,-soname,BFC.so.$(VER) -o $(LIBOUT)/BFC.so.$(VER) $(ALL_RELEASE_OBJ)
	$(LINKER) $(LINKEROPTIONS) /OUT:$(LIBOUT)/BFC.lib $(ALL_RELEASE_OBJ)

install: installd release
	cp $(LIBOUT)/BFC.so.$(VER) $(LIBINSTALL)/BFC.so.$(VER)
	rm -f $(LIBINSTALL)/BFC.so
	link $(LIBINSTALL)/BFC.so.$(VER) $(LIBINSTALL)/BFC.so

installd: debug
	cp $(LIBOUT)/BFC_d.so.$(VER) $(LIBINSTALL)/BFC_d.so.$(VER)
	rm -f $(LIBINSTALL)/BFC_d.so
	link $(LIBINSTALL)/BFC_d.so.$(VER) $(LIBINSTALL)/BFC_d.so

uninstall:
	rm -f $(LIBINSTALL)/BFC_d.so
	rm -f $(LIBINSTALL)/BFC_d.so.$(VER)
	rm -f $(LIBINSTALL)/BFC.so
	rm -f $(LIBINSTALL)/BFC.so.$(VER)

check_headers : $(ALL_H)
	$(CCPP) -E $(CPPFLAGS) ../include/BFC.h > junk




Debug\Bfc_DebugStatic.o : ../src\Bfc_DebugStatic.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\Bfc_DebugStatic.o ../src\Bfc_DebugStatic.cpp

Release\Bfc_DebugStatic.o : ../src\Bfc_DebugStatic.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\Bfc_DebugStatic.o ../src\Bfc_DebugStatic.cpp

Debug\CBfc_2dRect.o : ../src\CBfc_2dRect.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_2dRect.o ../src\CBfc_2dRect.cpp

Release\CBfc_2dRect.o : ../src\CBfc_2dRect.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_2dRect.o ../src\CBfc_2dRect.cpp

Debug\CBfc_2dSize.o : ../src\CBfc_2dSize.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_2dSize.o ../src\CBfc_2dSize.cpp

Release\CBfc_2dSize.o : ../src\CBfc_2dSize.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_2dSize.o ../src\CBfc_2dSize.cpp

Debug\CBfc_Angle.o : ../src\CBfc_Angle.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_Angle.o ../src\CBfc_Angle.cpp

Release\CBfc_Angle.o : ../src\CBfc_Angle.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_Angle.o ../src\CBfc_Angle.cpp

Debug\CBfc_Array.o : ../src\CBfc_Array.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_Array.o ../src\CBfc_Array.cpp

Release\CBfc_Array.o : ../src\CBfc_Array.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_Array.o ../src\CBfc_Array.cpp

Debug\CBfc_CompressionAlgorythm.o : ../src\CBfc_CompressionAlgorythm.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_CompressionAlgorythm.o ../src\CBfc_CompressionAlgorythm.cpp

Release\CBfc_CompressionAlgorythm.o : ../src\CBfc_CompressionAlgorythm.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_CompressionAlgorythm.o ../src\CBfc_CompressionAlgorythm.cpp

Debug\CBfc_Distance.o : ../src\CBfc_Distance.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_Distance.o ../src\CBfc_Distance.cpp

Release\CBfc_Distance.o : ../src\CBfc_Distance.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_Distance.o ../src\CBfc_Distance.cpp

Debug\CBfc_DynamicLink.o : ../src\CBfc_DynamicLink.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_DynamicLink.o ../src\CBfc_DynamicLink.cpp

Release\CBfc_DynamicLink.o : ../src\CBfc_DynamicLink.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_DynamicLink.o ../src\CBfc_DynamicLink.cpp

Debug\CBfc_Exception.o : ../src\CBfc_Exception.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_Exception.o ../src\CBfc_Exception.cpp

Release\CBfc_Exception.o : ../src\CBfc_Exception.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_Exception.o ../src\CBfc_Exception.cpp

Debug\CBfc_File.o : ../src\CBfc_File.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_File.o ../src\CBfc_File.cpp

Release\CBfc_File.o : ../src\CBfc_File.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_File.o ../src\CBfc_File.cpp

Debug\CBfc_Filename.o : ../src\CBfc_Filename.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_Filename.o ../src\CBfc_Filename.cpp

Release\CBfc_Filename.o : ../src\CBfc_Filename.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_Filename.o ../src\CBfc_Filename.cpp

Debug\CBfc_LinkedList.o : ../src\CBfc_LinkedList.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_LinkedList.o ../src\CBfc_LinkedList.cpp

Release\CBfc_LinkedList.o : ../src\CBfc_LinkedList.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_LinkedList.o ../src\CBfc_LinkedList.cpp

Debug\CBfc_MatrixDoubles.o : ../src\CBfc_MatrixDoubles.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_MatrixDoubles.o ../src\CBfc_MatrixDoubles.cpp

Release\CBfc_MatrixDoubles.o : ../src\CBfc_MatrixDoubles.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_MatrixDoubles.o ../src\CBfc_MatrixDoubles.cpp

Debug\CBfc_PointSpace3d.o : ../src\CBfc_PointSpace3d.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_PointSpace3d.o ../src\CBfc_PointSpace3d.cpp

Release\CBfc_PointSpace3d.o : ../src\CBfc_PointSpace3d.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_PointSpace3d.o ../src\CBfc_PointSpace3d.cpp

Debug\CBfc_PointSpaceTime.o : ../src\CBfc_PointSpaceTime.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_PointSpaceTime.o ../src\CBfc_PointSpaceTime.cpp

Release\CBfc_PointSpaceTime.o : ../src\CBfc_PointSpaceTime.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_PointSpaceTime.o ../src\CBfc_PointSpaceTime.cpp

Debug\CBfc_PointTime.o : ../src\CBfc_PointTime.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_PointTime.o ../src\CBfc_PointTime.cpp

Release\CBfc_PointTime.o : ../src\CBfc_PointTime.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_PointTime.o ../src\CBfc_PointTime.cpp

Debug\CBfc_Range2d.o : ../src\CBfc_Range2d.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_Range2d.o ../src\CBfc_Range2d.cpp

Release\CBfc_Range2d.o : ../src\CBfc_Range2d.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_Range2d.o ../src\CBfc_Range2d.cpp

Debug\CBfc_ReferencedAllocation.o : ../src\CBfc_ReferencedAllocation.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_ReferencedAllocation.o ../src\CBfc_ReferencedAllocation.cpp

Release\CBfc_ReferencedAllocation.o : ../src\CBfc_ReferencedAllocation.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_ReferencedAllocation.o ../src\CBfc_ReferencedAllocation.cpp

Debug\CBfc_ReferencedObject.o : ../src\CBfc_ReferencedObject.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_ReferencedObject.o ../src\CBfc_ReferencedObject.cpp

Release\CBfc_ReferencedObject.o : ../src\CBfc_ReferencedObject.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_ReferencedObject.o ../src\CBfc_ReferencedObject.cpp

Debug\CBfc_ReferencedPointer.o : ../src\CBfc_ReferencedPointer.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_ReferencedPointer.o ../src\CBfc_ReferencedPointer.cpp

Release\CBfc_ReferencedPointer.o : ../src\CBfc_ReferencedPointer.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_ReferencedPointer.o ../src\CBfc_ReferencedPointer.cpp

Debug\CBfc_Registry.o : ../src\CBfc_Registry.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_Registry.o ../src\CBfc_Registry.cpp

Release\CBfc_Registry.o : ../src\CBfc_Registry.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_Registry.o ../src\CBfc_Registry.cpp

Debug\CBfc_Stream.o : ../src\CBfc_Stream.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_Stream.o ../src\CBfc_Stream.cpp

Release\CBfc_Stream.o : ../src\CBfc_Stream.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_Stream.o ../src\CBfc_Stream.cpp

Debug\CBfc_StreamSource.o : ../src\CBfc_StreamSource.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_StreamSource.o ../src\CBfc_StreamSource.cpp

Release\CBfc_StreamSource.o : ../src\CBfc_StreamSource.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_StreamSource.o ../src\CBfc_StreamSource.cpp

Debug\CBfc_String.o : ../src\CBfc_String.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_String.o ../src\CBfc_String.cpp

Release\CBfc_String.o : ../src\CBfc_String.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_String.o ../src\CBfc_String.cpp

Debug\CBfc_String8.o : ../src\CBfc_String8.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_String8.o ../src\CBfc_String8.cpp

Release\CBfc_String8.o : ../src\CBfc_String8.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_String8.o ../src\CBfc_String8.cpp

Debug\CBfc_Value.o : ../src\CBfc_Value.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\CBfc_Value.o ../src\CBfc_Value.cpp

Release\CBfc_Value.o : ../src\CBfc_Value.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\CBfc_Value.o ../src\CBfc_Value.cpp

Debug\character.o : ../src\character.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\character.o ../src\character.cpp

Release\character.o : ../src\character.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\character.o ../src\character.cpp

Debug\Rect2dU.o : ../src\Rect2dU.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\Rect2dU.o ../src\Rect2dU.cpp

Release\Rect2dU.o : ../src\Rect2dU.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\Rect2dU.o ../src\Rect2dU.cpp

Debug\Size2dU.o : ../src\Size2dU.cpp 
		$(CCPP) -c $(CPPFLAGS) $(CPPDEBUG) /FoDebug\Size2dU.o ../src\Size2dU.cpp

Release\Size2dU.o : ../src\Size2dU.cpp 
		$(CCPP) -c $(CPPFLAGS) /FoRelease\Size2dU.o ../src\Size2dU.cpp
